// AUTO-GENERATED by scripts/gen-component-tokens.mjs — do not edit.
// Source: src/tokens/components/*.css. Run `pnpm check:mcp-token-sync`.

export interface ComponentToken {
  name: string;
  value: string;
  description: string;
}

export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    "name": "--badge-space-gap",
    "value": "var(--space-inline-xs)",
    "description": "Badge component tokens."
  },
  {
    "name": "--badge-space-x",
    "value": "var(--space-2)",
    "description": "Badge component tokens."
  },
  {
    "name": "--badge-space-y",
    "value": "var(--space-1)",
    "description": "Badge component tokens."
  },
  {
    "name": "--badge-font-size",
    "value": "var(--font-size-xs)",
    "description": "Small-by-design (badge/pill/counter). A knob (rule #45) so a service can * re-tune badge text without touching the global --font-size-xs step."
  },
  {
    "name": "--card-space-inset",
    "value": "var(--space-section-active)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-space-header-y",
    "value": "var(--space-stack-sm)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-space-body-y",
    "value": "var(--space-section-active)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-space-footer-y",
    "value": "var(--space-stack-sm)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-space-gap",
    "value": "var(--space-stack-xs)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-title-font-size",
    "value": "var(--font-size-base)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-title-line-height",
    "value": "var(--line-height-tight)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-title-font-weight",
    "value": "var(--font-weight-semibold)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-description-font-size",
    "value": "var(--font-size-sm)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-description-line-height",
    "value": "var(--line-height-normal)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-background",
    "value": "var(--card)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-border",
    "value": "var(--border)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-header-background",
    "value": "var(--muted)",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-header-background-alpha",
    "value": "0.55",
    "description": "Card component tokens: card chrome derives from semantic layout tokens."
  },
  {
    "name": "--card-header-border-bottom",
    "value": "1px solid hsl(var(--card-border))",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--card-radius",
    "value": "var(--radius)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-label-font-weight",
    "value": "var(--font-weight-medium)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-label-letter-spacing",
    "value": "0.04em",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-value-font-size",
    "value": "var(--font-size-2xl)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-value-line-height",
    "value": "1.1",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-value-font-weight",
    "value": "var(--font-weight-semibold)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-hint-font-size",
    "value": "var(--font-size-xs)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-gap",
    "value": "var(--space-stack-xs)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-icon-size",
    "value": "2.25rem",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--stat-card-delta-font-size",
    "value": "var(--font-size-xs)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--control-height-compact",
    "value": "1.75rem",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height-default",
    "value": "2rem",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height-comfortable",
    "value": "2.75rem",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-padding-x-compact",
    "value": "var(--space-2)",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-padding-x-default",
    "value": "var(--space-3)",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-padding-x-comfortable",
    "value": "var(--space-4)",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height",
    "value": "var(--control-height-default)",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height-sm",
    "value": "calc(var(--control-height) - 0.25rem)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-height-lg",
    "value": "calc(var(--control-height) + 0.25rem)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-height-xs",
    "value": "calc(var(--control-height) - 0.5rem)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-padding-x",
    "value": "var(--control-padding-x-default)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-gap",
    "value": "var(--space-inline-sm)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-gap-sm",
    "value": "var(--space-inline-xs)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-radius",
    "value": "var(--radius)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-icon-size",
    "value": "1rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-icon-size-sm",
    "value": "0.875rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-focus-ring-width",
    "value": "2px",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--checkbox-size",
    "value": "1rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--checkbox-size-compact",
    "value": "0.875rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--checkbox-size-comfortable",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--choice-gap",
    "value": "var(--space-inline-sm)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--choice-group-gap-x",
    "value": "var(--space-6)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--choice-group-gap-y",
    "value": "var(--space-3)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--choice-description-gap",
    "value": "0.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--choice-control-offset",
    "value": "0.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-width",
    "value": "2.25rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-width-compact",
    "value": "2rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-width-comfortable",
    "value": "2.5rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-height",
    "value": "1.25rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-height-compact",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-height-comfortable",
    "value": "1.375rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-thumb-size",
    "value": "1rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-thumb-size-compact",
    "value": "0.875rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-thumb-size-comfortable",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-thumb-translate",
    "value": "1rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-thumb-translate-compact",
    "value": "0.875rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--switch-thumb-translate-comfortable",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--slider-track-height",
    "value": "0.375rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--slider-thumb-size",
    "value": "1rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--color-picker-input-width",
    "value": "6.5rem",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--command-list-max-height",
    "value": "min(300px, 50vh)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--command-input-padding-x",
    "value": "var(--space-3)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--command-group-padding",
    "value": "var(--space-1)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--command-item-padding-y",
    "value": "var(--space-2)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--command-item-padding-x",
    "value": "var(--space-2)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--search-input-edge-inset",
    "value": "var(--space-3)",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--search-input-start-padding",
    "value": "calc( var(--search-input-edge-inset) + var(--control-icon-size) + var(--control-gap) )",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--search-input-end-padding",
    "value": "calc( var(--search-input-edge-inset) + var(--control-icon-size) + var(--control-gap) )",
    "description": "Adjacent control sizes, derived from the active --control-height. * Default/compact use a 4px/8px step; density overrides comfortable * (which steps 44→36→32 per the design's spacing-density spec)."
  },
  {
    "name": "--control-height-compact",
    "value": "2.75rem",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--control-height-default",
    "value": "2.75rem",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--choice-description-font-size",
    "value": "var(--font-size-xs)",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--color-picker-hex-font-size",
    "value": "var(--font-size-xs)",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--command-group-heading-font-size",
    "value": "var(--font-size-xs)",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--search-input-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--tag-input-chip-font-size",
    "value": "var(--font-size-xs)",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--toggle-sm-font-size",
    "value": "var(--font-size-xs)",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--button-sm-font-size",
    "value": "var(--font-size-xs)",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--progress-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--tree-item-title-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--tree-item-description-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--timeline-note-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--password-strength-score-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-entry component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--password-strength-checklist-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-entry component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--dialog-space-x",
    "value": "var(--space-chrome-x)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-space-y",
    "value": "var(--space-chrome-y)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-space-inset",
    "value": "var(--dialog-space-y) var(--dialog-space-x)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-space-gap",
    "value": "var(--space-stack-md)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-close-space-offset",
    "value": "var(--space-4)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-space-inset",
    "value": "var(--space-section-active)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-space-gap",
    "value": "var(--space-inline-md)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-inner-space-gap",
    "value": "var(--space-stack-sm)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-dismiss-space-offset",
    "value": "var(--space-3)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-bg-alpha",
    "value": "0.05",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--alert-border-alpha",
    "value": "0.3",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--empty-state-space-y",
    "value": "var(--space-10)",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--empty-state-space-x",
    "value": "var(--space-6)",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--skeleton-row-gap",
    "value": "var(--space-stack-sm)",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--skeleton-cell-gap",
    "value": "var(--space-inline-lg)",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--skeleton-card-inset",
    "value": "var(--space-section-active)",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--skeleton-radius",
    "value": "var(--radius)",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--form-label-width",
    "value": "max-content",
    "description": "Width of the label column in horizontal/inline layout. A service theme sets * this once (e.g. 110px) to align every form to its design grid; the Form/ * FormField `labelWidth` prop overrides per form/field."
  },
  {
    "name": "--form-label-gap",
    "value": "var(--space-4)",
    "description": "Column gap between the label and its control in horizontal/inline layout."
  },
  {
    "name": "--pagination-gap",
    "value": "var(--space-inline-sm)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--pagination-item-gap",
    "value": "var(--space-inline-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--pagination-size-width",
    "value": "5.5rem",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--pagination-total-font-size",
    "value": "var(--font-size-sm)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-bar-gap",
    "value": "var(--space-3)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-bar-padding-y",
    "value": "var(--space-2)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-picker-width-sm",
    "value": "11rem",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-picker-width-md",
    "value": "14rem",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--breadcrumb-font-size",
    "value": "var(--font-size-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--menubar-shortcut-font-size",
    "value": "var(--font-size-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--sidebar-section-label-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-product-tenant-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-badge-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-user-role-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-nav-sub-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-flyout-title-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--topbar-chip-icon-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--kbd-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-logo-mark-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-avatar-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-user-name-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--table-row-height-compact",
    "value": "1.75rem",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-row-height-default",
    "value": "2rem",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-row-height-comfortable",
    "value": "2.75rem",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-row-height",
    "value": "var(--table-row-height-default)",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-cell-padding-y",
    "value": "var(--space-2)",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-cell-space-x",
    "value": "var(--control-padding-x)",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-head-font-size",
    "value": "var(--font-size-xs)",
    "description": "Table component tokens: row height, cell padding."
  }
];
