// AUTO-GENERATED by scripts/gen-component-tokens.mjs — do not edit.
// Source: src/tokens/components/*.css. Run `pnpm check:mcp-token-sync`.

export interface ComponentToken {
  name: string;
  value: string;
  description: string;
}

export const COMPONENT_TOKENS: ComponentToken[] = [
  {
    "name": "--badge-space-gap",
    "value": "var(--space-inline-xs)",
    "description": "Badge component tokens."
  },
  {
    "name": "--badge-space-x",
    "value": "var(--space-2)",
    "description": "Badge component tokens."
  },
  {
    "name": "--badge-space-y",
    "value": "var(--space-1)",
    "description": "Badge component tokens."
  },
  {
    "name": "--badge-font-size",
    "value": "var(--font-size-xs)",
    "description": "Small-by-design (badge/pill/counter). A knob (rule #45) so a service can * re-tune badge text without touching the global --font-size-xs step."
  },
  {
    "name": "--card-space-inset",
    "value": "var(--space-section-active)",
    "description": "Horizontal inset of every slot (header / content / footer) + the resting top/bottom * shell padding. This is the column the title, body and footer all align to."
  },
  {
    "name": "--card-space-header-y",
    "value": "var(--space-stack-sm)",
    "description": "Vertical padding of a BANDED header band (top = bottom). Drives --card-space-divided-y."
  },
  {
    "name": "--card-space-body-y",
    "value": "var(--space-section-active)",
    "description": "Gap between the header and the body, and the body's own top padding — the breathing * room under a title before content begins."
  },
  {
    "name": "--card-space-footer-y",
    "value": "var(--space-stack-sm)",
    "description": "Vertical padding of a SEPARATED footer band (top = bottom). Drives --card-space-divided-y."
  },
  {
    "name": "--card-space-divided-y",
    "value": "var(--card-space-header-y)",
    "description": "DIVIDED-section vertical padding (rule #44/#45). A header/footer that carries a divider * border (banded header, separated footer) reads as its own band, so it pads SYMMETRICALLY * top+bottom — distinct from a plain header that flows into the body (top inset, no bottom). * One themeable knob keeps the header- and footer-band rhythm in sync; a service theme tunes * the band density here instead of forking per-slot CSS."
  },
  {
    "name": "--card-space-gap",
    "value": "var(--space-stack-xs)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-title-font-size",
    "value": "var(--font-size-base)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-title-line-height",
    "value": "var(--line-height-tight)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-title-font-weight",
    "value": "var(--font-weight-semibold)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-description-font-size",
    "value": "var(--font-size-sm)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-description-line-height",
    "value": "var(--line-height-normal)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-background",
    "value": "var(--card)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-border",
    "value": "var(--border)",
    "description": "Vertical gap between stacked items WITHIN a slot (e.g. title ↕ description in the header)."
  },
  {
    "name": "--card-header-background",
    "value": "var(--muted)",
    "description": "Banded-header fill — already role-tintable (rule #45): a service points this at any role, * e.g. --card-header-background: var(--primary), and tunes --card-header-background-alpha for * the wash strength. No separate tint token needed."
  },
  {
    "name": "--card-header-background-alpha",
    "value": "0.55",
    "description": "Banded-header fill — already role-tintable (rule #45): a service points this at any role, * e.g. --card-header-background: var(--primary), and tunes --card-header-background-alpha for * the wash strength. No separate tint token needed."
  },
  {
    "name": "--card-header-border-bottom",
    "value": "1px solid hsl(var(--card-border))",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--card-radius",
    "value": "var(--radius)",
    "description": "Banded-header divider — tokenised (rule #44) so a service theme can make it * dashed / heavier / none without forking CSS. Pair with * --card-header-background-alpha: 0 for a quiet borderless-band header."
  },
  {
    "name": "--card-shadow",
    "value": "0 0 0 0 transparent",
    "description": "Resting elevation — quiet by default (rule #44): cards are flat (1px border, no shadow) in the * dxs-kintai baseline. A service that wants lifted cards sets this to an elevation token once, * e.g. --card-shadow: var(--shadow-sm), and every Card picks up the shadow with no markup change."
  },
  {
    "name": "--card-glow",
    "value": "0 0 0 0 transparent",
    "description": "Brand glow layer — invisible no-op at rest (rule #44). Paired AFTER --card-shadow in the * surface box-shadow so a service can wash every card with the global glow, e.g. * --card-glow: var(--shadow-glow), with no markup change."
  },
  {
    "name": "--card-tint",
    "value": "transparent",
    "description": "Fill tint — subtle role wash over the card background (default transparent = invisible). * Painted as an overlay so a service sets --card-tint: hsl(var(--primary) / 0.04) once."
  },
  {
    "name": "--card-accent-rail-width",
    "value": "6px",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-label-font-weight",
    "value": "var(--font-weight-medium)",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-label-letter-spacing",
    "value": "0.04em",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-value-font-size",
    "value": "var(--font-size-2xl)",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-value-line-height",
    "value": "1.1",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-value-font-weight",
    "value": "var(--font-weight-semibold)",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-hint-font-size",
    "value": "var(--font-size-xs)",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-gap",
    "value": "var(--space-stack-xs)",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-icon-size",
    "value": "2.25rem",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--stat-card-delta-font-size",
    "value": "var(--font-size-xs)",
    "description": "Accent edge — width of the semantic leading-edge stripe (data-accent). * Tokenised (rule #44) so a service theme can re-tune it without forking CSS. * The slot padding compensation in card-layout.css subtracts the same token, * so content stays aligned on the shell whatever the rail width."
  },
  {
    "name": "--control-height-compact",
    "value": "1.75rem",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height-default",
    "value": "2rem",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height-comfortable",
    "value": "2.75rem",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-padding-x-compact",
    "value": "var(--space-2)",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-padding-x-default",
    "value": "var(--space-3)",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-padding-x-comfortable",
    "value": "var(--space-4)",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height",
    "value": "calc(var(--control-height-default) * var(--scaling))",
    "description": "Control primitive tokens: heights, horizontal padding, adjacent control sizes."
  },
  {
    "name": "--control-height-sm",
    "value": "calc(var(--control-height) - calc(0.25rem * var(--scaling)))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-height-lg",
    "value": "calc(var(--control-height) + calc(0.25rem * var(--scaling)))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-height-xs",
    "value": "calc(var(--control-height) - calc(0.5rem * var(--scaling)))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-padding-x",
    "value": "var(--control-padding-x-default)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-gap",
    "value": "var(--space-inline-sm)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-gap-sm",
    "value": "var(--space-inline-xs)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-radius",
    "value": "var(--radius)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-icon-size",
    "value": "calc(1rem * var(--scaling))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-icon-size-sm",
    "value": "calc(0.875rem * var(--scaling))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--control-focus-ring-width",
    "value": "var(--focus-ring-width)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--checkbox-size",
    "value": "calc(1rem * var(--scaling))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--checkbox-size-compact",
    "value": "0.875rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--checkbox-size-comfortable",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--choice-gap",
    "value": "var(--space-inline-sm)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--choice-group-gap-x",
    "value": "var(--space-6)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--choice-group-gap-y",
    "value": "var(--space-3)",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--choice-description-gap",
    "value": "0.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--choice-control-offset",
    "value": "0.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-width",
    "value": "calc(2.25rem * var(--scaling))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-width-compact",
    "value": "2rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-width-comfortable",
    "value": "2.5rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-height",
    "value": "calc(1.25rem * var(--scaling))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-height-compact",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-height-comfortable",
    "value": "1.375rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-thumb-size",
    "value": "calc(1rem * var(--scaling))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-thumb-size-compact",
    "value": "0.875rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-thumb-size-comfortable",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-thumb-translate",
    "value": "calc(1rem * var(--scaling))",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-thumb-translate-compact",
    "value": "0.875rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--switch-thumb-translate-comfortable",
    "value": "1.125rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--slider-track-height",
    "value": "0.375rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--slider-thumb-size",
    "value": "1rem",
    "description": "Adjacent control sizes, derived from the active --control-height. The ±step * is scaled too so the whole control ladder stays proportional under --scaling."
  },
  {
    "name": "--checkbox-checked-background",
    "value": "hsl(var(--primary))",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--switch-checked-background",
    "value": "hsl(var(--primary))",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--toggle-on-background",
    "value": "hsl(var(--primary))",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--slider-track-background",
    "value": "hsl(var(--primary) / 0.2)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--slider-range-background",
    "value": "hsl(var(--primary))",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--color-picker-input-width",
    "value": "6.5rem",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--command-list-max-height",
    "value": "min(300px, 50vh)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--command-input-padding-x",
    "value": "var(--space-3)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--command-group-padding",
    "value": "var(--space-1)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--command-item-padding-y",
    "value": "var(--space-2)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--command-item-padding-x",
    "value": "var(--space-2)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--search-input-edge-inset",
    "value": "var(--space-3)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--search-input-start-padding",
    "value": "calc( var(--search-input-edge-inset) + var(--control-icon-size) + var(--control-gap) )",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--search-input-end-padding",
    "value": "calc( var(--search-input-edge-inset) + var(--control-icon-size) + var(--control-gap) )",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--choice-description-font-size",
    "value": "var(--font-size-xs)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--color-picker-hex-font-size",
    "value": "var(--font-size-xs)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--command-group-heading-font-size",
    "value": "var(--font-size-xs)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--search-input-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--tag-input-chip-font-size",
    "value": "var(--font-size-xs)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--toggle-sm-font-size",
    "value": "var(--font-size-xs)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--button-sm-font-size",
    "value": "var(--font-size-xs)",
    "description": "Checked/on/active fills — themeable role expression, defaults equal the current literal * (quiet: no visual change). A service retints the \"selected\" state by overriding these."
  },
  {
    "name": "--control-height-compact",
    "value": "2.75rem",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--control-height-default",
    "value": "2.75rem",
    "description": "Rule #24 — on touch devices (coarse pointer) interactive controls keep a ≥44px tap target * regardless of density; desktop (fine pointer) keeps the compact heights above. --control-height * resolves through these via var(), so inputs/buttons/selects/table rows all bump together."
  },
  {
    "name": "--progress-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--tree-item-title-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--tree-item-description-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--timeline-note-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-display component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--avatar-background",
    "value": "hsl(var(--muted))",
    "description": "Avatar surface — reads the muted role by default. A service can re-tint the placeholder fill once (e.g. --avatar-background: hsl(var(--accent)))."
  },
  {
    "name": "--avatar-tint",
    "value": "transparent",
    "description": "Optional role wash over the avatar (default transparent = invisible, rule #44). Painted as an overlay so a service sets --avatar-tint: hsl(var(--primary) / 0.08)."
  },
  {
    "name": "--progress-track-background",
    "value": "hsl(var(--secondary))",
    "description": "Progress track + fill — quiet defaults equal the current literals (rule #44). Track reads secondary, fill reads success; a service re-tones once."
  },
  {
    "name": "--progress-fill-background",
    "value": "hsl(var(--success))",
    "description": "Progress track + fill — quiet defaults equal the current literals (rule #44). Track reads secondary, fill reads success; a service re-tones once."
  },
  {
    "name": "--timeline-dot-done-background",
    "value": "hsl(var(--success))",
    "description": "Timeline accents — dot/line roles, defaults unchanged (rule #44)."
  },
  {
    "name": "--timeline-dot-current-background",
    "value": "hsl(var(--primary))",
    "description": "Timeline accents — dot/line roles, defaults unchanged (rule #44)."
  },
  {
    "name": "--timeline-line-completed-background",
    "value": "hsl(var(--primary))",
    "description": "Timeline accents — dot/line roles, defaults unchanged (rule #44)."
  },
  {
    "name": "--tree-item-active-border",
    "value": "hsl(var(--primary) / 0.3)",
    "description": "Tree active item — border + soft bg tint over the primary role. Defaults equal the current literals (rule #44)."
  },
  {
    "name": "--tree-item-active-background",
    "value": "hsl(var(--primary) / 0.05)",
    "description": "Tree active item — border + soft bg tint over the primary role. Defaults equal the current literals (rule #44)."
  },
  {
    "name": "--password-strength-score-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-entry component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--password-strength-checklist-font-size",
    "value": "var(--font-size-xs)",
    "description": "Data-entry component tokens — small-by-design text knobs (rule #45/#46)."
  },
  {
    "name": "--descriptions-label-width",
    "value": "8rem",
    "description": "Width of the label column when <Descriptions layout=\"horizontal\">. Labels align to this * shared column so the values line up (the horizontal-detail look, mirroring <Form layout>). * A rem value gives a fixed aligned column; set `max-content` to size each label to its text. * (rule #44/#45 — a service theme tunes it here instead of forking CSS.)"
  },
  {
    "name": "--dialog-space-x",
    "value": "var(--space-chrome-x)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-space-y",
    "value": "var(--space-chrome-y)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-space-inset",
    "value": "var(--dialog-space-y) var(--dialog-space-x)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-space-gap",
    "value": "var(--space-stack-md)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--dialog-close-space-offset",
    "value": "var(--space-4)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-space-inset",
    "value": "var(--space-section-active)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-space-gap",
    "value": "var(--space-inline-md)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-inner-space-gap",
    "value": "var(--space-stack-sm)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-dismiss-space-offset",
    "value": "var(--space-3)",
    "description": "Dialog inset defaults to the shared global chrome tokens (override --space-chrome-* once for the * whole system, or --dialog-space-x/-y for dialogs only)."
  },
  {
    "name": "--alert-bg-alpha",
    "value": "0.05",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--alert-border-alpha",
    "value": "0.3",
    "description": "Soft (subtle) semantic tint ratios — themeable so a service can hit its exact spec * (a brand's success-bg/-border are often more present than the faint 5%/30% default)."
  },
  {
    "name": "--dialog-content-glow",
    "value": "0 0 0 0 transparent",
    "description": "Brand glow layer for the raised dialog/sheet panel — invisible no-op at rest (rule #44). * Paired AFTER --shadow-lg in the surface box-shadow so a service can wash the overlay with the * global glow, e.g. --dialog-content-glow: var(--shadow-glow), with no markup change."
  },
  {
    "name": "--empty-state-space-y",
    "value": "var(--space-10)",
    "description": "Brand glow layer for the raised dialog/sheet panel — invisible no-op at rest (rule #44). * Paired AFTER --shadow-lg in the surface box-shadow so a service can wash the overlay with the * global glow, e.g. --dialog-content-glow: var(--shadow-glow), with no markup change."
  },
  {
    "name": "--empty-state-space-x",
    "value": "var(--space-6)",
    "description": "Brand glow layer for the raised dialog/sheet panel — invisible no-op at rest (rule #44). * Paired AFTER --shadow-lg in the surface box-shadow so a service can wash the overlay with the * global glow, e.g. --dialog-content-glow: var(--shadow-glow), with no markup change."
  },
  {
    "name": "--empty-state-icon-foreground",
    "value": "hsl(var(--muted-foreground))",
    "description": "EmptyState icon medallion colour — defaults to the current literal (rule #44), so a service can * recolour the glyph (--icon-foreground) or wash the medallion fill (--icon-tint) without forking."
  },
  {
    "name": "--empty-state-icon-tint",
    "value": "hsl(var(--muted))",
    "description": "EmptyState icon medallion colour — defaults to the current literal (rule #44), so a service can * recolour the glyph (--icon-foreground) or wash the medallion fill (--icon-tint) without forking."
  },
  {
    "name": "--skeleton-row-gap",
    "value": "var(--space-stack-sm)",
    "description": "EmptyState icon medallion colour — defaults to the current literal (rule #44), so a service can * recolour the glyph (--icon-foreground) or wash the medallion fill (--icon-tint) without forking."
  },
  {
    "name": "--skeleton-cell-gap",
    "value": "var(--space-inline-lg)",
    "description": "EmptyState icon medallion colour — defaults to the current literal (rule #44), so a service can * recolour the glyph (--icon-foreground) or wash the medallion fill (--icon-tint) without forking."
  },
  {
    "name": "--skeleton-card-inset",
    "value": "var(--space-section-active)",
    "description": "EmptyState icon medallion colour — defaults to the current literal (rule #44), so a service can * recolour the glyph (--icon-foreground) or wash the medallion fill (--icon-tint) without forking."
  },
  {
    "name": "--skeleton-radius",
    "value": "var(--radius)",
    "description": "EmptyState icon medallion colour — defaults to the current literal (rule #44), so a service can * recolour the glyph (--icon-foreground) or wash the medallion fill (--icon-tint) without forking."
  },
  {
    "name": "--skeleton-background",
    "value": "hsl(var(--muted))",
    "description": "Skeleton placeholder fill — defaults to the current literal hsl(var(--muted)); themeable so a * service can tint the shimmer to its surface (rule #44) without forking the keyframes."
  },
  {
    "name": "--form-label-width",
    "value": "max-content",
    "description": "Width of the label column in horizontal/inline layout. A service theme sets * this once (e.g. 110px) to align every form to its design grid; the Form/ * FormField `labelWidth` prop overrides per form/field."
  },
  {
    "name": "--form-label-gap",
    "value": "var(--space-4)",
    "description": "Column gap between the label and its control in horizontal/inline layout."
  },
  {
    "name": "--list-row-padding-y",
    "value": "var(--space-3)",
    "description": "ListRow component tokens — a single-line entity row for short lists inside a Card * (sessions / API tokens / linked accounts / passkeys …). Sits in a flush CardContent; * rows separate with a quiet divider (#44 — chrome defaults to the calm semantic border)."
  },
  {
    "name": "--list-row-padding-x",
    "value": "var(--space-4)",
    "description": "ListRow component tokens — a single-line entity row for short lists inside a Card * (sessions / API tokens / linked accounts / passkeys …). Sits in a flush CardContent; * rows separate with a quiet divider (#44 — chrome defaults to the calm semantic border)."
  },
  {
    "name": "--list-row-gap",
    "value": "var(--space-3)",
    "description": "ListRow component tokens — a single-line entity row for short lists inside a Card * (sessions / API tokens / linked accounts / passkeys …). Sits in a flush CardContent; * rows separate with a quiet divider (#44 — chrome defaults to the calm semantic border)."
  },
  {
    "name": "--list-row-border",
    "value": "1px solid hsl(var(--border))",
    "description": "ListRow component tokens — a single-line entity row for short lists inside a Card * (sessions / API tokens / linked accounts / passkeys …). Sits in a flush CardContent; * rows separate with a quiet divider (#44 — chrome defaults to the calm semantic border)."
  },
  {
    "name": "--pagination-gap",
    "value": "var(--space-inline-sm)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--pagination-item-gap",
    "value": "var(--space-inline-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--pagination-size-width",
    "value": "5.5rem",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--pagination-total-font-size",
    "value": "var(--font-size-sm)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-bar-gap",
    "value": "var(--space-3)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-bar-padding-y",
    "value": "var(--space-2)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-label-font-size",
    "value": "var(--font-size-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-picker-width-sm",
    "value": "11rem",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--filter-picker-width-md",
    "value": "14rem",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--breadcrumb-font-size",
    "value": "var(--font-size-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--menubar-shortcut-font-size",
    "value": "var(--font-size-xs)",
    "description": "Navigation primitive tokens: pagination, filters, compact pickers."
  },
  {
    "name": "--menubar-item-hover-background",
    "value": "hsl(var(--accent))",
    "description": "Menu item hover/highlight tint — reads the accent role; default unchanged."
  },
  {
    "name": "--menubar-item-hover-foreground",
    "value": "hsl(var(--accent-foreground))",
    "description": "Menu item hover/highlight tint — reads the accent role; default unchanged."
  },
  {
    "name": "--sidebar-section-label-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-product-tenant-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-badge-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-user-role-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-nav-sub-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-flyout-title-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--topbar-chip-icon-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--kbd-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-logo-mark-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-avatar-font-size",
    "value": "var(--font-size-2xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-user-name-font-size",
    "value": "var(--font-size-xs)",
    "description": "Shell (sidebar / topbar / kbd) component tokens — small-by-design text * knobs (rule #45/#46). A service re-tunes chrome text without moving the * global scale."
  },
  {
    "name": "--sidebar-gradient",
    "value": "none",
    "description": "Brand-chrome gradient hooks — opt-in, invisible by default. A service paints * the sidebar/topbar surface by setting these to a gradient (no-op = none)."
  },
  {
    "name": "--topbar-gradient",
    "value": "none",
    "description": "Brand-chrome gradient hooks — opt-in, invisible by default. A service paints * the sidebar/topbar surface by setting these to a gradient (no-op = none)."
  },
  {
    "name": "--sidebar-item-active-color",
    "value": "hsl(var(--primary))",
    "description": "Sidebar active-item tint/marker — tokenised from the literal hsl(var(--primary)) * usages; defaults are byte-identical to the prior hard-coded values. A service * can re-tune the active sub-item accent without forking CSS."
  },
  {
    "name": "--sidebar-item-active-tint",
    "value": "hsl(var(--primary))",
    "description": "Sidebar active-item tint/marker — tokenised from the literal hsl(var(--primary)) * usages; defaults are byte-identical to the prior hard-coded values. A service * can re-tune the active sub-item accent without forking CSS."
  },
  {
    "name": "--table-row-height-compact",
    "value": "1.75rem",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-row-height-default",
    "value": "2rem",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-row-height-comfortable",
    "value": "2.75rem",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-row-height",
    "value": "calc(var(--table-row-height-default) * var(--scaling))",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-cell-padding-y",
    "value": "var(--space-2)",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-cell-space-x",
    "value": "var(--control-padding-x)",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-head-font-size",
    "value": "var(--font-size-xs)",
    "description": "Table component tokens: row height, cell padding."
  },
  {
    "name": "--table-pin-shadow",
    "value": "-6px 0 6px -5px hsl(var(--foreground) / 0.12)",
    "description": "Inline-end shadow that lifts a pinned (sticky) action column off the body it scrolls over."
  },
  {
    "name": "--table-row-striped-background",
    "value": "hsl(var(--muted) / 0.4)",
    "description": "Row-state tint washes — translucent muted over the opaque base. Defaults equal * the prior literals; a service retints by reading another role (e.g. --primary)."
  },
  {
    "name": "--table-row-hover-background",
    "value": "hsl(var(--muted) / 0.5)",
    "description": "Row-state tint washes — translucent muted over the opaque base. Defaults equal * the prior literals; a service retints by reading another role (e.g. --primary)."
  },
  {
    "name": "--table-row-selected-background",
    "value": "hsl(var(--muted) / 0.3)",
    "description": "Row-state tint washes — translucent muted over the opaque base. Defaults equal * the prior literals; a service retints by reading another role (e.g. --primary)."
  }
];
