// AUTO-GENERATED by scripts/gen-email-tokens.mjs — do not edit.
// Sources: src/tokens/foundation.css (colour roles) + src/tokens/components/email.css (geometry).
// Run `node scripts/gen-email-tokens.mjs` (guard: `node scripts/gen-email-tokens.mjs --check`).

/** One email colour slot and the web role it is derived from. `hsl` is the raw channel triplet. */
export interface EmailColorSource {
  /** The semantic role in src/tokens/foundation.css this slot mirrors. */
  readonly cssVar: string;
  /** The role's HSL channel triplet, verbatim (`H S% L%`). Converted to hex at module load. */
  readonly hsl: string;
}

/** Light-scheme colour sources — the canonical transactional-email palette. */
export const EMAIL_COLOR_SOURCE = {
  "background": {
    "cssVar": "--background",
    "hsl": "60 33% 99%"
  },
  "foreground": {
    "cssVar": "--foreground",
    "hsl": "48 8% 13%"
  },
  "surface": {
    "cssVar": "--card",
    "hsl": "60 33% 99%"
  },
  "surfaceForeground": {
    "cssVar": "--card-foreground",
    "hsl": "48 8% 13%"
  },
  "muted": {
    "cssVar": "--muted",
    "hsl": "45 15% 95%"
  },
  "mutedForeground": {
    "cssVar": "--muted-foreground",
    "hsl": "44 5% 39%"
  },
  "border": {
    "cssVar": "--border",
    "hsl": "30 7% 93%"
  },
  "primary": {
    "cssVar": "--primary",
    "hsl": "268.7 100% 50%"
  },
  "primaryForeground": {
    "cssVar": "--primary-foreground",
    "hsl": "60 33% 99%"
  },
  "focus": {
    "cssVar": "--primary",
    "hsl": "268.7 100% 50%"
  },
  "brand": {
    "cssVar": "--brand",
    "hsl": "268.7 100% 50%"
  },
  "brandForeground": {
    "cssVar": "--brand-foreground",
    "hsl": "60 33% 99%"
  },
  "urgency": {
    "cssVar": "--attention",
    "hsl": "25 99% 46%"
  },
  "urgencyForeground": {
    "cssVar": "--attention-foreground",
    "hsl": "60 33% 99%"
  }
} as const;

/** Dark-scheme colour sources, for `@media (prefers-color-scheme: dark)` overrides. */
export const EMAIL_COLOR_SOURCE_DARK = {
  "background": {
    "cssVar": "--background",
    "hsl": "48 9% 9%"
  },
  "foreground": {
    "cssVar": "--foreground",
    "hsl": "60 20% 96%"
  },
  "surface": {
    "cssVar": "--card",
    "hsl": "48 8% 12%"
  },
  "surfaceForeground": {
    "cssVar": "--card-foreground",
    "hsl": "60 20% 96%"
  },
  "muted": {
    "cssVar": "--muted",
    "hsl": "45 6% 18%"
  },
  "mutedForeground": {
    "cssVar": "--muted-foreground",
    "hsl": "44 6% 64%"
  },
  "border": {
    "cssVar": "--border",
    "hsl": "45 6% 19%"
  },
  "primary": {
    "cssVar": "--primary",
    "hsl": "268.7 100% 86.9%"
  },
  "primaryForeground": {
    "cssVar": "--primary-foreground",
    "hsl": "48 9% 9%"
  },
  "focus": {
    "cssVar": "--primary",
    "hsl": "268.7 100% 86.9%"
  },
  "brand": {
    "cssVar": "--brand",
    "hsl": "268.7 100% 86.9%"
  },
  "brandForeground": {
    "cssVar": "--brand-foreground",
    "hsl": "48 9% 9%"
  },
  "urgency": {
    "cssVar": "--attention",
    "hsl": "25 95% 56%"
  },
  "urgencyForeground": {
    "cssVar": "--attention-foreground",
    "hsl": "48 9% 9%"
  }
} as const;

/** Raw `--email-*` declarations from the component token tier, verbatim. */
export const EMAIL_GEOMETRY_SOURCE = {
  "--email-shell-width": "480px",
  "--email-shell-padding": "32px",
  "--email-shell-page-padding": "24px",
  "--email-shell-border-width": "1px",
  "--email-card-radius": "10px",
  "--email-card-reference-height": "407px",
  "--email-stack-gap": "24px",
  "--email-stack-gap-sm": "12px",
  "--email-mark-width": "22px",
  "--email-mark-height": "22px",
  "--email-mark-gap": "8px",
  "--email-wordmark-font-size": "13px",
  "--email-wordmark-font-weight": "700",
  "--email-font-family-sans": "'Noto Sans JP', 'Hiragino Sans', 'Hiragino Kaku Gothic ProN', 'Yu Gothic Medium', YuGothic, 'M PLUS 2', Meiryo, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, system-ui, Arial, sans-serif",
  "--email-font-family-mono": "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
  "--email-body-font-size": "14px",
  "--email-body-line-height": "1.9",
  "--email-body-font-weight": "400",
  "--email-heading-font-size": "17px",
  "--email-heading-line-height": "1.7",
  "--email-heading-font-weight": "500",
  "--email-cta-height": "44px",
  "--email-cta-line-height": "44px",
  "--email-cta-padding-x": "16px",
  "--email-cta-radius": "6px",
  "--email-cta-font-size": "14px",
  "--email-cta-font-weight": "500",
  "--email-footer-font-size": "11px",
  "--email-footer-line-height": "1.8",
  "--email-footer-link-gap": "12px",
  "--email-footer-padding-top": "20px",
  "--email-footer-border-width": "1px",
  "--email-focus-border-width": "2px",
  "--email-mobile-max-width": "520px",
  "--email-mobile-width": "100%",
  "--email-mobile-padding": "20px",
  "--email-mobile-page-padding": "12px",
  "--email-mobile-heading-font-size": "16px",
  "--email-mobile-cta-width": "100%"
} as const;

/**
 * The GoDX identity artwork — the same two paths `<Logo mark="godx" />` paints, from
 * `src/brand/godx-mark.ts`. Regenerate with the rest of this file; `--check` fails on drift.
 */
export const EMAIL_MARK_SOURCE = {
  "viewBox": "0 0 32 32",
  "transform": "translate(0 3.917) scale(0.132780)",
  "bodyPath": "M93.0 0.0H158.0C161.0 0.0 162.0 1.0 164.0 3.0L197.0 41.0Q201.0 46.0 195.0 46.0H97.0C71.0 46.0 50.0 68.0 50.0 94.0C50.0 119.0 72.0 138.0 97.0 138.0H126.0Q132.0 138.0 128.0 143.0L95.0 180.0Q93.0 182.0 90.0 182.0C65.0 182.0 44.0 171.0 25.0 151.0C7.0 132.0 0.0 115.0 0.0 94.0C0.0 69.0 11.0 52.0 31.0 31.0C52.0 9.0 70.0 0.0 93.0 0.0Z",
  "arrowPath": "M106.0 74.0H219.0Q222.0 74.0 224.0 77.0L239.0 94.0Q243.0 99.0 239.0 104.0L169.0 178.0Q165.0 182.0 160.0 182.0H114.0Q108.0 182.0 112.0 178.0L151.0 137.0Q154.0 134.0 151.0 131.0L104.0 81.0Q98.0 74.0 106.0 74.0Z"
} as const;
