// AUTO-GENERATED by scripts/gen-email-tokens.mjs — do not edit.
// Sources: src/tokens/foundation.css (colour roles) + src/tokens/components/email.css (geometry).
// Run `node scripts/gen-email-tokens.mjs` (guard: `pnpm check:email-token-sync`).

/** One email colour slot and the web role it is derived from. `hsl` is the raw channel triplet. */
export interface EmailColorSource {
  /** The semantic role in src/tokens/foundation.css this slot mirrors. */
  readonly cssVar: string;
  /** The role's HSL channel triplet, verbatim (`H S% L%`). Converted to hex at module load. */
  readonly hsl: string;
}

/** Light-scheme colour sources — the canonical transactional-email palette. */
export const EMAIL_COLOR_SOURCE = {
  "background": {
    "cssVar": "--background",
    "hsl": "60 33% 99%"
  },
  "foreground": {
    "cssVar": "--foreground",
    "hsl": "48 8% 13%"
  },
  "surface": {
    "cssVar": "--card",
    "hsl": "60 33% 99%"
  },
  "surfaceForeground": {
    "cssVar": "--card-foreground",
    "hsl": "48 8% 13%"
  },
  "muted": {
    "cssVar": "--muted",
    "hsl": "45 15% 95%"
  },
  "mutedForeground": {
    "cssVar": "--muted-foreground",
    "hsl": "44 5% 42%"
  },
  "border": {
    "cssVar": "--border",
    "hsl": "30 7% 83%"
  },
  "primary": {
    "cssVar": "--primary",
    "hsl": "204 100% 39%"
  },
  "primaryForeground": {
    "cssVar": "--primary-foreground",
    "hsl": "60 33% 99%"
  },
  "focus": {
    "cssVar": "--ring",
    "hsl": "204 100% 39%"
  },
  "brand": {
    "cssVar": "--success",
    "hsl": "146 40% 58%"
  },
  "brandForeground": {
    "cssVar": "--success-foreground",
    "hsl": "60 33% 99%"
  }
} as const;

/** Dark-scheme colour sources, for `@media (prefers-color-scheme: dark)` overrides. */
export const EMAIL_COLOR_SOURCE_DARK = {
  "background": {
    "cssVar": "--background",
    "hsl": "48 9% 9%"
  },
  "foreground": {
    "cssVar": "--foreground",
    "hsl": "60 20% 96%"
  },
  "surface": {
    "cssVar": "--card",
    "hsl": "48 8% 12%"
  },
  "surfaceForeground": {
    "cssVar": "--card-foreground",
    "hsl": "60 20% 96%"
  },
  "muted": {
    "cssVar": "--muted",
    "hsl": "45 6% 18%"
  },
  "mutedForeground": {
    "cssVar": "--muted-foreground",
    "hsl": "44 6% 64%"
  },
  "border": {
    "cssVar": "--border",
    "hsl": "45 6% 22%"
  },
  "primary": {
    "cssVar": "--primary",
    "hsl": "204 90% 60%"
  },
  "primaryForeground": {
    "cssVar": "--primary-foreground",
    "hsl": "48 9% 9%"
  },
  "focus": {
    "cssVar": "--ring",
    "hsl": "204 90% 60%"
  },
  "brand": {
    "cssVar": "--success",
    "hsl": "146 45% 55%"
  },
  "brandForeground": {
    "cssVar": "--success-foreground",
    "hsl": "48 9% 9%"
  }
} as const;

/** Raw `--email-*` declarations from the component token tier, verbatim. */
export const EMAIL_GEOMETRY_SOURCE = {
  "--email-shell-width": "480px",
  "--email-shell-padding": "32px",
  "--email-shell-page-padding": "24px",
  "--email-shell-border-width": "1px",
  "--email-card-radius": "10px",
  "--email-card-reference-height": "407px",
  "--email-stack-gap": "24px",
  "--email-stack-gap-sm": "12px",
  "--email-mark-width": "32px",
  "--email-mark-height": "32px",
  "--email-font-family-sans": "-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Helvetica Neue, Arial, sans-serif",
  "--email-body-font-size": "14px",
  "--email-body-line-height": "1.7",
  "--email-body-font-weight": "400",
  "--email-heading-font-size": "20px",
  "--email-heading-line-height": "1.25",
  "--email-heading-font-weight": "700",
  "--email-cta-height": "44px",
  "--email-cta-line-height": "44px",
  "--email-cta-padding-x": "24px",
  "--email-cta-radius": "6px",
  "--email-cta-font-size": "14px",
  "--email-cta-font-weight": "700",
  "--email-footer-font-size": "12px",
  "--email-footer-line-height": "1.5",
  "--email-footer-link-gap": "12px",
  "--email-footer-padding-top": "20px",
  "--email-footer-border-width": "1px",
  "--email-focus-border-width": "2px",
  "--email-mobile-max-width": "520px",
  "--email-mobile-width": "100%",
  "--email-mobile-padding": "20px",
  "--email-mobile-page-padding": "12px",
  "--email-mobile-heading-font-size": "18px",
  "--email-mobile-cta-width": "100%"
} as const;
