import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const script = join(process.cwd(), "scripts/ui-audit.mjs");

function audit(source: string, framework = false, path?: string, filename = "sample.tsx") {
  const cwd = mkdtempSync(join(tmpdir(), "godx-ui-audit-"));
  try {
    writeFileSync(
      join(cwd, "package.json"),
      JSON.stringify({ name: framework ? "@godxjp/ui" : "consumer" }),
    );
    const directory = path ?? (framework ? "src" : "resources/js/pages");
    mkdirSync(join(cwd, directory), { recursive: true });
    writeFileSync(join(cwd, directory, filename), source);
    const result = spawnSync(process.execPath, [script, "--format", "json"], {
      cwd,
      encoding: "utf8",
    });
    return { status: result.status, output: result.stdout };
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
}

describe("consumer audit CLI regressions", () => {
  it("distinguishes framework test support and API prose from shipped JSX", () => {
    expect(audit("<button>Fixture</button>", true, "src/test").output).not.toContain(
      '"no-raw-button"',
    );
    expect(audit("<button>Action</button>", true, "src/pages").output).toContain('"no-raw-button"');
    expect(
      audit(
        'const description = "A <button> owns the action — never a link";',
        true,
        "src/props",
        "registry.ts",
      ).status,
    ).toBe(0);
    expect(audit('console.warn("Missing name — check your props");').output).not.toContain(
      '"no-em-dash-in-copy"',
    );
    expect(audit("<Text>First\n — second</Text>").output).toContain('"no-em-dash-in-copy"');
    expect(audit('<Input placeholder="—" />').output).not.toContain('"no-em-dash-in-copy"');
    expect(audit('<Input placeholder="First — second" />').output).toContain(
      '"no-em-dash-in-copy"',
    );
  });

  it("allows physical animation directions but still catches physical layout", () => {
    expect(audit('const classes = "data-[side=left]:slide-in-from-right-2";').output).not.toContain(
      '"no-physical-direction"',
    );
    expect(audit('const classes = "slide-in-from-right-2 pr-4";').output).toContain(
      '"no-physical-direction"',
    );
    expect(
      audit(
        '/* rtl-ignore: sheet side names a physical edge */\nconst classes = "right-0 border-l";',
      ).output,
    ).not.toContain('"no-physical-direction"');
  });

  it("recognizes compiled email tokens without allowing handwritten overrides", () => {
    const source =
      '// AUTO-GENERATED by scripts/gen-email-tokens.mjs — do not edit.\nconst tokens = { "--email-shell-padding": "32px" };';
    expect(audit(source, true, "src/email", "tokens.generated.ts").output).not.toContain(
      '"no-off-scale-token-value"',
    );
    expect(audit(source, false, "resources/js/pages", "tokens.generated.ts").output).toContain(
      '"no-off-scale-token-value"',
    );
    expect(
      audit(
        'const tokens = { "--email-shell-padding": "32px" };',
        true,
        "src/email",
        "tokens.generated.ts",
      ).output,
    ).toContain('"no-off-scale-token-value"');
  });

  it("does not interpret template substitutions or comparisons as currency text", () => {
    expect(
      audit("const html = `<p>${copy}</p>`;", true, "docs/foundation", "email.ts").output,
    ).not.toContain('"hardcoded-currency"');
    expect(
      audit("<Calendar footer={days.length > 0 ? `Selected: ${days.length}` : null} />").output,
    ).not.toContain('"hardcoded-currency"');
    expect(audit('<Text title={count > 0 ? "yes" : "no"}>${amount}</Text>').output).toContain(
      '"hardcoded-currency"',
    );
  });
  it("reads class-shaped rules from class expressions only, not prose (#406)", () => {
    // Copy, an i18n value or a JSX text node that merely SPELLS a utility is not a class.
    expect(audit("const note = 'chuỗi có chữ gap-3 trong đó';").output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<Text>văn bản JSX nhắc gap-3</Text>").output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit('const messages = { hint: "Total gap-3 items" };').output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit('<Text title="Spacing: use gap-3">Read me</Text>').output).not.toContain(
      '"no-utility-spacing"',
    );
    // …and the text of an element that DOES carry a class is still only text.
    const mixed = audit('<div className="flex">gap-3 items</div>').output;
    expect(mixed).toContain('"no-utility-layout"');
    expect(mixed).not.toContain('"no-utility-spacing"');
  });

  it("still catches a class wherever a class can actually be written (#406)", () => {
    expect(audit('<div className="gap-3" />').output).toContain('"no-utility-spacing"');
    expect(audit('<div className={cn("gap-3", isWide && "p-2")} />').output).toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<div className={clsx(\n  active && `gap-3`,\n)} />").output).toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<div className={`pr-4 ${extra}`} />").output).toContain(
      '"no-physical-direction"',
    );
    expect(audit('const baseClass = "space-x-2";').output).toContain('"no-space-xy"');
    expect(audit('const columns = [{ className: "text-white" }];').output).toContain(
      '"raw-white-black"',
    );
    // A class MAP under its conventional names — the shape `cva()` is not used for.
    expect(
      audit('const statusStyles: Record<string, string> = {\n  spam: "bg-red-100",\n};').output,
    ).toContain('"no-raw-palette-color"');
    expect(audit('const badgeVariants = {\n  lead: "dark:bg-red-500/15",\n};').output).toContain(
      '"no-dark-color-override"',
    );
  });

  it("suppresses a block only when a reason is given, and only for that rule (#406)", () => {
    const block = (begin: string) =>
      audit(
        `${begin}\nconst aClass = "gap-3";\nconst bClass = "p-2";\n// ui-audit-disable-end no-utility-spacing\nconst cClass = "gap-4";`,
      );

    // Reason present → one marker covers every line of the block.
    const suppressed = block(
      "// ui-audit-disable-begin no-utility-spacing — legacy grid, tracked in gh#123",
    );
    expect(suppressed.output).toContain('"line": 5'); // the line AFTER the block still reports
    expect(suppressed.output.match(/"no-utility-spacing"/g)).toHaveLength(1);

    // Reason missing, or too short to say anything → the finding stands on all three lines.
    for (const begin of [
      "// ui-audit-disable-begin no-utility-spacing",
      "// ui-audit-disable-begin no-utility-spacing — why",
    ]) {
      expect(block(begin).output.match(/"no-utility-spacing"/g), begin).toHaveLength(3);
    }

    // A block names ONE rule; every other rule keeps reporting inside it.
    const scoped = audit(
      "// ui-audit-disable-begin no-utility-spacing — spacing is deliberate here\n" +
        'const aClass = "gap-3 bg-red-500";\n' +
        "// ui-audit-disable-end no-utility-spacing",
    );
    expect(scoped.output).not.toContain('"no-utility-spacing"');
    expect(scoped.output).toContain('"no-raw-palette-color"');

    // An unclosed block runs to the end of the file.
    expect(
      audit(
        "// ui-audit-disable-begin no-utility-spacing — whole fixture is legacy markup\n" +
          'const aClass = "gap-3";\nconst bClass = "p-2";',
      ).output,
    ).not.toContain('"no-utility-spacing"');
  });

  it("scans framework defaults and still detects a violation", () => {
    const result = audit('<input type="text" />', true);
    expect(result.status).toBe(1);
    expect(result.output).toContain('"no-raw-input"');
    expect(result.output).toContain("src/sample.tsx");
  });

  it("allows primitive native controls without exempting consumer screens or docs", () => {
    expect(audit('<input type="text" />', true, "src/components/data-entry").status).toBe(0);
    expect(audit('<input type="text" />', true, "docs/data-entry").output).toContain(
      '"no-raw-input"',
    );
    expect(audit('<input type="text" />', false, "resources/js/pages").output).toContain(
      '"no-raw-input"',
    );
  });

  it("allows hidden form encoding but rejects visible and unknown input types", () => {
    expect(audit('<input\n name="id"\n type="hidden" value="7" />').status).toBe(0);
    expect(audit("<input type='hidden' name='id' />").status).toBe(0);
    for (const source of [
      '<input type="text" />',
      "<input\n type={kind}\n />",
      "<input />",
      "<input hidden />",
    ]) {
      expect(audit(source).output, source).toContain('"no-raw-input"');
    }
  });

  it("does not mistake Markdown interpolation for JSX currency", () => {
    expect(audit("const quote = lines.map((line) => `> ${line}`);").status).toBe(0);
    expect(audit("<Button onClick={() => router.post(`/view/${id}`)}>Save</Button>").status).toBe(
      0,
    );
    for (const source of [
      "<Text>${amount}</Text>",
      '<Text\n tone="muted">\n¥{amount}</Text>',
      "<Text>{amount}円</Text>",
      "<Text>Total: ${amount}</Text>",
      "<>${amount}</>",
      '<Text title="a > b">${amount}</Text>',
      "<Button onClick={() => save()}>${amount}</Button>",
    ]) {
      expect(audit(source).output, source).toContain('"hardcoded-currency"');
    }
  });
});

it("rejects Select onChange and accepts the supported value callback", () => {
  expect(audit("<Select options={options} onChange={setValue} />").output).toContain(
    '"value-callback-on-value-change"',
  );
  expect(audit("<Select options={options} onValueChange={setValue} />").output).not.toContain(
    '"value-callback-on-value-change"',
  );
});
