import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const script = join(process.cwd(), "scripts/ui-audit.mjs");

function audit(source: string, framework = false, path?: string, filename = "sample.tsx") {
  const cwd = mkdtempSync(join(tmpdir(), "godx-ui-audit-"));
  try {
    writeFileSync(
      join(cwd, "package.json"),
      JSON.stringify({ name: framework ? "@godxjp/ui" : "consumer" }),
    );
    const directory = path ?? (framework ? "src" : "resources/js/pages");
    mkdirSync(join(cwd, directory), { recursive: true });
    writeFileSync(join(cwd, directory, filename), source);
    const result = spawnSync(process.execPath, [script, "--format", "json"], {
      cwd,
      encoding: "utf8",
    });
    return { status: result.status, output: result.stdout };
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
}

describe("consumer audit CLI regressions", () => {
  /**
   * `\p{Extended_Pictographic}` covers U+00A9 ©, U+00AE ® and U+2122 ™, and all three are
   * `Emoji_Presentation=No` — typographic marks that predate emoji and default to text
   * presentation. None of the reasons in the rule's own message reaches them: a copyright line
   * does not break on Win/Linux and does not pollute an accessible name. The catalog's own
   * CenteredShell recipe was flagged for the `©` in its footer, and so is every consumer that
   * ships one.
   *
   * With U+FE0F after them they are asking for emoji presentation on purpose, so they stay caught.
   */
  it("does not call ©, ® or ™ an emoji, but still catches them with a VS16 selector", () => {
    expect(audit("<Text>\u00a9 2026 GodX</Text>").output).not.toContain('"no-emoji-in-ui"');
    expect(audit("<Text>Acme\u2122 \u00ae</Text>").output).not.toContain('"no-emoji-in-ui"');
    expect(audit("<Text>\u00a9\ufe0f 2026</Text>").output).toContain('"no-emoji-in-ui"');
    expect(audit("<Text>Shipped \u2705</Text>").output).toContain('"no-emoji-in-ui"');
    expect(audit("<Text>\ud83c\udf89</Text>").output).toContain('"no-emoji-in-ui"');
  });

  it("distinguishes framework test support and API prose from shipped JSX", () => {
    expect(audit("<button>Fixture</button>", true, "src/test").output).not.toContain(
      '"no-raw-button"',
    );
    expect(audit("<button>Action</button>", true, "src/pages").output).toContain('"no-raw-button"');
    expect(
      audit(
        'const description = "A <button> owns the action — never a link";',
        true,
        "src/props",
        "registry.ts",
      ).status,
    ).toBe(0);
    expect(audit('console.warn("Missing name — check your props");').output).not.toContain(
      '"no-em-dash-in-copy"',
    );
    expect(audit("<Text>First\n — second</Text>").output).toContain('"no-em-dash-in-copy"');
    expect(audit('<Input placeholder="—" />').output).not.toContain('"no-em-dash-in-copy"');
    expect(audit('<Input placeholder="First — second" />').output).toContain(
      '"no-em-dash-in-copy"',
    );
  });

  it("allows physical animation directions but still catches physical layout", () => {
    expect(audit('const classes = "data-[side=left]:slide-in-from-right-2";').output).not.toContain(
      '"no-physical-direction"',
    );
    expect(audit('const classes = "slide-in-from-right-2 pr-4";').output).toContain(
      '"no-physical-direction"',
    );
    expect(
      audit(
        '/* rtl-ignore: sheet side names a physical edge */\nconst classes = "right-0 border-l";',
      ).output,
    ).not.toContain('"no-physical-direction"');
  });

  it("recognizes compiled email tokens without allowing handwritten overrides", () => {
    const source =
      '// AUTO-GENERATED by scripts/gen-email-tokens.mjs — do not edit.\nconst tokens = { "--email-shell-padding": "32px" };';
    expect(audit(source, true, "src/email", "tokens.generated.ts").output).not.toContain(
      '"no-off-scale-token-value"',
    );
    expect(audit(source, false, "resources/js/pages", "tokens.generated.ts").output).toContain(
      '"no-off-scale-token-value"',
    );
    expect(
      audit(
        'const tokens = { "--email-shell-padding": "32px" };',
        true,
        "src/email",
        "tokens.generated.ts",
      ).output,
    ).toContain('"no-off-scale-token-value"');
  });

  it("does not interpret template substitutions or comparisons as currency text", () => {
    expect(
      audit("const html = `<p>${copy}</p>`;", true, "docs/foundation", "email.ts").output,
    ).not.toContain('"hardcoded-currency"');
    expect(
      audit("<Calendar footer={days.length > 0 ? `Selected: ${days.length}` : null} />").output,
    ).not.toContain('"hardcoded-currency"');
    expect(audit('<Text title={count > 0 ? "yes" : "no"}>${amount}</Text>').output).toContain(
      '"hardcoded-currency"',
    );
  });
  it("reads class-shaped rules from class expressions only, not prose (#406)", () => {
    // Copy, an i18n value or a JSX text node that merely SPELLS a utility is not a class.
    expect(audit("const note = 'chuỗi có chữ gap-3 trong đó';").output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<Text>văn bản JSX nhắc gap-3</Text>").output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit('const messages = { hint: "Total gap-3 items" };').output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit('<Text title="Spacing: use gap-3">Read me</Text>').output).not.toContain(
      '"no-utility-spacing"',
    );
    // …and the text of an element that DOES carry a class is still only text.
    const mixed = audit('<div className="flex">gap-3 items</div>').output;
    expect(mixed).toContain('"no-utility-layout"');
    expect(mixed).not.toContain('"no-utility-spacing"');
  });

  it("still catches a class wherever a class can actually be written (#406)", () => {
    expect(audit('<div className="gap-3" />').output).toContain('"no-utility-spacing"');
    expect(audit('<div className={cn("gap-3", isWide && "p-2")} />').output).toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<div className={clsx(\n  active && `gap-3`,\n)} />").output).toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<div className={`pr-4 ${extra}`} />").output).toContain(
      '"no-physical-direction"',
    );
    expect(audit('const baseClass = "space-x-2";').output).toContain('"no-space-xy"');
    expect(audit('const columns = [{ className: "text-white" }];').output).toContain(
      '"raw-white-black"',
    );
    // A class MAP under its conventional names — the shape `cva()` is not used for.
    expect(
      audit('const statusStyles: Record<string, string> = {\n  spam: "bg-red-100",\n};').output,
    ).toContain('"no-raw-palette-color"');
    expect(audit('const badgeVariants = {\n  lead: "dark:bg-red-500/15",\n};').output).toContain(
      '"no-dark-color-override"',
    );
  });

  it("suppresses a block only when a reason is given, and only for that rule (#406)", () => {
    const block = (begin: string) =>
      audit(
        `${begin}\nconst aClass = "gap-3";\nconst bClass = "p-2";\n// ui-audit-disable-end no-utility-spacing\nconst cClass = "gap-4";`,
      );

    // Reason present → one marker covers every line of the block.
    const suppressed = block(
      "// ui-audit-disable-begin no-utility-spacing — legacy grid, tracked in gh#123",
    );
    expect(suppressed.output).toContain('"line": 5'); // the line AFTER the block still reports
    expect(suppressed.output.match(/"no-utility-spacing"/g)).toHaveLength(1);

    // Reason missing, or too short to say anything → the finding stands on all three lines.
    for (const begin of [
      "// ui-audit-disable-begin no-utility-spacing",
      "// ui-audit-disable-begin no-utility-spacing — why",
    ]) {
      expect(block(begin).output.match(/"no-utility-spacing"/g), begin).toHaveLength(3);
    }

    // A block names ONE rule; every other rule keeps reporting inside it.
    const scoped = audit(
      "// ui-audit-disable-begin no-utility-spacing — spacing is deliberate here\n" +
        'const aClass = "gap-3 bg-red-500";\n' +
        "// ui-audit-disable-end no-utility-spacing",
    );
    expect(scoped.output).not.toContain('"no-utility-spacing"');
    expect(scoped.output).toContain('"no-raw-palette-color"');

    // An unclosed block runs to the end of the file.
    expect(
      audit(
        "// ui-audit-disable-begin no-utility-spacing — whole fixture is legacy markup\n" +
          'const aClass = "gap-3";\nconst bClass = "p-2";',
      ).output,
    ).not.toContain('"no-utility-spacing"');
  });

  it("scans framework defaults and still detects a violation", () => {
    const result = audit('<input type="text" />', true);
    expect(result.status).toBe(1);
    expect(result.output).toContain('"no-raw-input"');
    expect(result.output).toContain("src/sample.tsx");
  });

  it("allows primitive native controls without exempting consumer screens or docs", () => {
    expect(audit('<input type="text" />', true, "src/components/data-entry").status).toBe(0);
    expect(audit('<input type="text" />', true, "docs/data-entry").output).toContain(
      '"no-raw-input"',
    );
    expect(audit('<input type="text" />', false, "resources/js/pages").output).toContain(
      '"no-raw-input"',
    );
  });

  it("allows hidden form encoding but rejects visible and unknown input types", () => {
    expect(audit('<input\n name="id"\n type="hidden" value="7" />').status).toBe(0);
    expect(audit("<input type='hidden' name='id' />").status).toBe(0);
    for (const source of [
      '<input type="text" />',
      "<input\n type={kind}\n />",
      "<input />",
      "<input hidden />",
    ]) {
      expect(audit(source).output, source).toContain('"no-raw-input"');
    }
  });

  it("does not flag template URLs or generics as hardcoded currency (#601)", () => {
    const quiet = [
      "const result = await context.request<TurnResult>(`/chat/${queued.turn_id}`);",
      "const path = `/api/${id}/x`;",
      "const joined = `${a}-${b}`;",
      "const Box = styled.div`padding: ${space}px`;",
    ];
    for (const source of quiet) {
      expect(audit(source).output, source).not.toContain('"hardcoded-currency"');
    }
    expect(audit("<span>${price}円</span>").output).toContain('"hardcoded-currency"');
    expect(audit("<Text>¥{amount}</Text>").output).toContain('"hardcoded-currency"');
  });

  it("does not mistake Markdown interpolation for JSX currency", () => {
    expect(audit("const quote = lines.map((line) => `> ${line}`);").status).toBe(0);
    expect(audit("<Button onClick={() => router.post(`/view/${id}`)}>Save</Button>").status).toBe(
      0,
    );
    for (const source of [
      "<Text>${amount}</Text>",
      '<Text\n tone="muted">\n¥{amount}</Text>',
      "<Text>{amount}円</Text>",
      "<Text>Total: ${amount}</Text>",
      "<>${amount}</>",
      '<Text title="a > b">${amount}</Text>',
      "<Button onClick={() => save()}>${amount}</Button>",
    ]) {
      expect(audit(source).output, source).toContain('"hardcoded-currency"');
    }
  });
});

it("rejects Select onChange and accepts the supported value callback", () => {
  expect(audit("<Select options={options} onChange={setValue} />").output).toContain(
    '"value-callback-on-value-change"',
  );
  expect(audit("<Select options={options} onValueChange={setValue} />").output).not.toContain(
    '"value-callback-on-value-change"',
  );
});

describe("card composition (godx-jp/id#496, #498)", () => {
  it("does not call a Form-wrapped body a missing body", () => {
    // The only correct composition for a card whose submit button lives in CardFooter: the <form>
    // has to wrap the content AND the footer, or the button cannot submit it. The rule asked for a
    // Card slot as the IMMEDIATE next element, so it fired on correct code — three times, on a
    // consumer's newest file.
    const wrapped = [
      '<Card>\n<Form onSubmit={s}>\n<CardContent>body</CardContent>\n<CardFooter><Button type="submit">save</Button></CardFooter>\n</Form>\n</Card>',
      '<Card density="tight">\n<>\n<CardContent solo>body</CardContent>\n</>\n</Card>',
    ];

    for (const source of wrapped) {
      expect(audit(source).output, source).not.toContain('"card-needs-content"');
    }
  });

  it("still reports a card with no body at all", () => {
    expect(audit("<Card>\n<Table><tbody /></Table>\n</Card>").output).toContain(
      '"card-needs-content"',
    );
  });

  it("requires flush when the table IS the card body, and only then", () => {
    const bare =
      "<Card>\n<CardContent>\n<DataTable columns={c} data={d} />\n</CardContent>\n</Card>";
    const flush =
      "<Card>\n<CardContent flush>\n<DataTable columns={c} data={d} />\n</CardContent>\n</Card>";
    // A filter bar ABOVE the table makes the body mixed, and there the padding is correct — the
    // trap the reporter hit with a `childElementCount === 1` test.
    const mixed =
      '<Card>\n<CardContent>\n<Flex direction="col" gap="md">\n<FilterBar />\n<DataTable columns={c} data={d} />\n</Flex>\n</CardContent>\n</Card>';

    expect(audit(bare).output).toContain('"card-table-needs-flush"');
    expect(audit(flush).output).not.toContain('"card-table-needs-flush"');
    expect(audit(mixed).output).not.toContain('"card-table-needs-flush"');
  });
});

it("names the replacement primitive in the finding (godx-jp/id#497)", () => {
  // Without this the reader has to ask the catalog which component replaces what they just wrote —
  // one round-trip per finding, and a guess about what to look up.
  const out = audit(
    "<Card>\n<CardContent>\n<DataTable columns={c} data={d} />\n</CardContent>\n</Card>",
  ).output;

  expect(out).toContain('"replacement": "CardContent flush"');
  expect(audit('<button type="button">save</button>').output).toContain('"replacement": "Button"');
});

describe("owned rule file drift (godx-jp/id#513)", () => {
  /** A consumer tree whose `.ai/rules/godxjp-ui.md` claims `stamped` while the package is 23.0.0. */
  function consumerWithStamp(stamped: string) {
    const cwd = mkdtempSync(join(tmpdir(), "godx-ui-stale-"));
    writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: "consumer" }));
    mkdirSync(join(cwd, ".ai", "rules"), { recursive: true });
    mkdirSync(join(cwd, "node_modules", "@godxjp", "ui"), { recursive: true });
    mkdirSync(join(cwd, "resources", "js", "pages"), { recursive: true });
    writeFileSync(
      join(cwd, "node_modules", "@godxjp", "ui", "package.json"),
      JSON.stringify({ name: "@godxjp/ui", version: "23.0.0" }),
    );
    writeFileSync(
      join(cwd, ".ai", "rules", "godxjp-ui.md"),
      `<!-- godxjp-ui:version ${stamped} -->\n`,
    );
    writeFileSync(
      join(cwd, "resources", "js", "pages", "a.tsx"),
      "export const A = () => <Text>a</Text>;\n",
    );
    const result = spawnSync(process.execPath, [script, "--format", "json"], {
      cwd,
      encoding: "utf8",
    });
    rmSync(cwd, { recursive: true, force: true });
    return result.stdout;
  }

  it("reports a rule file three majors behind the package it documents", () => {
    // `ignore-scripts=true` blocks our postinstall, so the file that promises to be rewritten on
    // every upgrade silently is not. An agent then follows rules for components that were deleted.
    const out = consumerWithStamp("19.6.0");

    expect(out).toContain('"owned-rules-stale"');
    expect(out).toContain("19.6.0");
    expect(out).toContain("sync-rules");
  });

  it("says nothing when the file matches the installed package", () => {
    expect(consumerWithStamp("23.0.0")).not.toContain('"owned-rules-stale"');
  });
});

/**
 * gh#712 — a lucide glyph rendered where nothing will size it.
 *
 * A lucide component ships `width="24" height="24"` and four rules in this library override that,
 * three of them direct-child rules. Outside those four a glyph draws at 24px beside 14px text: the
 * one defect class that is invisible in review, because the JSX is correct and only the screen is
 * wrong. A consumer swept one app and found 38.
 */
describe("lucide-icon-needs-size (gh#712)", () => {
  /** Every finding of one rule, by line. ONE CLI run per source — see the gh#711 note above. */
  function report(source: string) {
    return (
      JSON.parse(audit(source).output) as { findings: { rule: string; line: number }[] }
    ).findings
      .filter((f) => f.rule === "lucide-icon-needs-size")
      .map((f) => f.line);
  }

  const IMPORT = 'import { Lock, Pencil as Edit } from "lucide-react";\n';

  it("fires on a bare glyph in a Text, a cell, a link and a Flex", () => {
    expect(report(`${IMPORT}<Text><Lock /> encrypted</Text>`)).toEqual([2]);
    expect(report(`${IMPORT}<Flex>\n  <Edit />\n</Flex>`)).toEqual([3]);
    expect(report(`${IMPORT}<a href="/x">\n  <Lock />\n</a>`)).toEqual([3]);
    // Prettier wraps a wide element, and the tag name then ends its own line (gh#673).
    expect(report(`${IMPORT}<Flex>\n  <Lock\n    strokeWidth={1.5}\n  />\n</Flex>`)).toEqual([3]);
  });

  it("stays quiet inside the four contexts that DO size a glyph", () => {
    const quiet = [
      `${IMPORT}<Button size="sm">\n  <Lock />\n  Export\n</Button>`,
      `${IMPORT}<DropdownMenuItem>\n  <Lock />\n  Lock\n</DropdownMenuItem>`,
      `${IMPORT}<TopbarItem aria-label="lock">\n  <Lock />\n</TopbarItem>`,
      // a glyph handed to a component through a named SLOT is that component's to size
      `${IMPORT}<ListRow leading={<Lock />} title="Vault" />`,
      `${IMPORT}<Alert icon={<Lock />} title="Locked" />`,
    ];
    for (const source of quiet) expect(report(source), source).toEqual([]);
  });

  it("stays quiet when the author has already said something about the box", () => {
    const quiet = [
      `${IMPORT}<Text><Lock size={16} /> encrypted</Text>`,
      `${IMPORT}<Text><Lock className="text-muted-foreground size-4" /> encrypted</Text>`,
      `${IMPORT}<Text><Lock width={16} height={16} /> encrypted</Text>`,
      // the primitive itself: `as={Lock}` is a reference, never an element
      `${IMPORT}<Text><Icon as={Lock} size="sm" /> encrypted</Text>`,
    ];
    for (const source of quiet) expect(report(source), source).toEqual([]);
  });

  it("only knows the names this file imported from lucide-react", () => {
    const quiet = [
      // a component of the consumer's own, PascalCase, never imported from lucide
      "<Flex>\n  <Lock />\n</Flex>",
      // the same name imported from somewhere else entirely
      'import { Lock } from "./icons";\n<Flex>\n  <Lock />\n</Flex>',
      // prose about markup is not markup
      `${IMPORT}const note = "render <Lock /> inside a Text";`,
    ];
    for (const source of quiet) expect(report(source), source).toEqual([]);
    // the rename is followed
    expect(report(`${IMPORT}<Text><Edit /> edit</Text>`)).toEqual([2]);
  });

  it("is a WARNING, so a false positive cannot block a review", () => {
    const findings = (
      JSON.parse(audit(`${IMPORT}<Text><Lock /> encrypted</Text>`).output) as {
        findings: { rule: string; severity: string }[];
      }
    ).findings.filter((f) => f.rule === "lucide-icon-needs-size");
    expect(findings).toHaveLength(1);
    expect(findings[0].severity).toBe("warn");
  });

  it("does not run inside this package, where a component sizes its own glyph", () => {
    // 90 findings measured here with the scope off, every one of them a component whose own
    // stylesheet carries the metric — the capability a consumer does not have.
    expect(report(`${IMPORT}<Flex>\n  <Lock />\n</Flex>`)).toEqual([3]);
    const framework = (
      JSON.parse(
        audit(`${IMPORT}<Flex>\n  <Lock />\n</Flex>`, true, "src/components/data-display").output,
      ) as { findings: { rule: string }[] }
    ).findings.filter((f) => f.rule === "lucide-icon-needs-size");
    expect(framework).toEqual([]);
  });
});

describe("an opening tag that ends its line is still an opening tag (gh#673)", () => {
  /** The line numbers one rule reports for a fixture. */
  function lines(source: string, rule: string, framework = false, path?: string) {
    const report = JSON.parse(audit(source, framework, path).output) as {
      findings: { rule: string; line: number }[];
    };
    return report.findings.filter((f) => f.rule === rule).map((f) => f.line);
  }

  /*
   * Prettier wraps any element wider than printWidth, which leaves `<button` alone on its line. The
   * control rules matched `/<button[\s>]/` ONE LINE at a time, and the newline that follows the tag
   * name is not part of that line, so every wrapped element was invisible. Measured in a consumer
   * app: 0 `no-raw-button` reported while ~166 multi-line `<button` remained.
   */
  it.each([
    [
      "no-raw-button",
      '<Flex>\n  <button\n    type="button"\n    onClick={() => go()}\n  >\n    Go\n  </button>\n</Flex>',
    ],
    [
      "no-raw-select",
      "<Flex>\n  <select\n    value={value}\n    onChange={(e) => set(e.target.value)}\n  >\n    <option />\n  </select>\n</Flex>",
    ],
    [
      "no-raw-input",
      '<Flex>\n  <input\n    type="checkbox"\n    checked={on}\n    onChange={(e) => set(e.target.checked)}\n  />\n</Flex>',
    ],
    ["no-raw-textarea", "<Flex>\n  <textarea\n    rows={3}\n    value={value}\n  />\n</Flex>"],
    [
      "no-raw-table",
      '<Flex>\n  <table\n    aria-label="rows"\n  >\n    <tbody />\n  </table>\n</Flex>',
    ],
  ])("%s reports a multi-line element on the line of its `<`", (rule, source) => {
    expect(lines(source, rule)).toEqual([2]);
  });

  it("still reports the single-line form, once per element", () => {
    expect(lines('<button type="button">Go</button>', "no-raw-button")).toEqual([1]);
    expect(lines("<select><option /></select>", "no-raw-select")).toEqual([1]);
    expect(lines("<table><tbody /></table>", "no-raw-table")).toEqual([1]);
    expect(lines("<textarea />", "no-raw-textarea")).toEqual([1]);
    expect(lines("<button/>", "no-raw-button")).toEqual([1]);
  });

  it("honours ui-audit-disable-next-line above a multi-line element, in both comment forms", () => {
    const element =
      '  <button\n    type="button"\n    onClick={() => go()}\n  >\n    Go\n  </button>';
    expect(
      lines(
        `<Flex>\n  {/* ui-audit-disable-next-line no-raw-button */}\n${element}\n</Flex>`,
        "no-raw-button",
      ),
    ).toEqual([]);
    expect(
      lines(
        `const x = (\n  // ui-audit-disable-next-line no-raw-button\n${element}\n);`,
        "no-raw-button",
      ),
    ).toEqual([]);
    // The directive names ONE rule and covers ONE line: another id, or a blank line between, does not.
    expect(
      lines(
        `<Flex>\n  {/* ui-audit-disable-next-line no-raw-select */}\n${element}\n</Flex>`,
        "no-raw-button",
      ),
    ).toEqual([3]);
    expect(
      lines(
        `<Flex>\n  {/* ui-audit-disable-next-line no-raw-button */}\n\n${element}\n</Flex>`,
        "no-raw-button",
      ),
    ).toEqual([4]);
  });

  it("does not match components, longer tag names, closing tags or comments", () => {
    const quiet = [
      '<ButtonGroup\n  size="sm"\n>\n  <Button\n    onClick={go}\n  >\n    Go\n  </Button>\n</ButtonGroup>',
      "<Input\n  value={v}\n/>",
      "<Select\n  value={v}\n  onValueChange={set}\n/>",
      "<buttonish\n  a={1}\n/>",
      "<inputs\n  a={1}\n/>",
      "<selection\n  a={1}\n/>",
      "<Flex>\n  {label}\n</button\n>",
      '/*\n * <button\n *   type="button"\n */\nconst a = 1;',
      "// <select\nconst b = 2;",
    ];
    // ONE audit per source, read for all three rules. This loop used to spawn the CLI once per
    // (source, rule) pair — 27 processes, measured past vitest's 8s default on a loaded CI runner,
    // which failed the 27.1.0 merge commit on load alone. The findings are the same either way.
    for (const source of quiet) {
      const report = JSON.parse(audit(source).output) as {
        findings: { rule: string; line: number }[];
      };
      for (const rule of ["no-raw-button", "no-raw-input", "no-raw-select"]) {
        const found = report.findings.filter((f) => f.rule === rule).map((f) => f.line);
        expect(found, `${rule}: ${source}`).toEqual([]);
      }
    }
  });

  it("keeps the framework's own primitives exempt, and nothing else", () => {
    const wrapped = '<button\n  type="button"\n/>';
    expect(lines(wrapped, "no-raw-button", true, "src/components/general")).toEqual([]);
    expect(lines(wrapped, "no-raw-button", true, "docs/general")).toEqual([1]);
  });

  /* The same line-bound defect, in the other rules anchored on something that can span lines. */
  it("manual-field-helper sees a wrapped <p>", () => {
    expect(
      lines(
        '<Flex>\n  <p\n    className="text-xs text-muted-foreground"\n  >\n    Hint\n  </p>\n</Flex>',
        "manual-field-helper",
      ),
    ).toEqual([2]);
  });

  it("hand-rolled-close-glyph sees a glyph on its own line, and still accepts a named one", () => {
    expect(
      lines(
        '<Flex>\n  <span className="close">\n    ×\n  </span>\n</Flex>',
        "hand-rolled-close-glyph",
      ),
    ).toEqual([2]);
    expect(
      lines(
        '<Flex>\n  <span aria-hidden="true">\n    ×\n  </span>\n  <VisuallyHidden>未実施</VisuallyHidden>\n</Flex>',
        "hand-rolled-close-glyph",
      ),
    ).toEqual([]);
  });

  /**
   * `no-hand-rolled-list` (gh#714). A consumer's settings menu and dashboard lost EVERY divider
   * because each row sat in a wrapper of its own, so `[data-slot="list-row"]:not(:last-child)`
   * never matched — silently, and review saw nothing.
   *
   * ONE CLI process per source, every case read off the same report (see the note above about 27
   * processes failing a merge on load alone).
   */
  it("flags a hand-rolled list, and stays quiet on the supported idiom", () => {
    const handRolled = [
      '<ul className="menu">',
      "  <li>prose bullet</li>",
      "</ul>",
      '<div role="list">',
      '  <div role="listitem">',
      '    <ListRow title="Two-factor" />',
      "  </div>",
      "</div>",
      "<li>",
      "  <Card />",
      "</li>",
    ].join("\n");
    // The raw container, both ARIA roles, and the wrapper around a library row — but NOT the
    // prose `<li>` on line 2, which is what a bulleted <Flex as="ul"> is FOR.
    expect(lines(handRolled, "no-hand-rolled-list")).toEqual([1, 4, 5, 9]);

    const supported = [
      '<Flex as="ul" marker="none" direction="col" gap="none">',
      '  <ListRow as="li" title="Two-factor" />',
      '  <ListRow as="li" title="Passkeys" />',
      "</Flex>",
      '<Flex as="ul" gap="xs">',
      "  <li>prose bullet</li>",
      "</Flex>",
    ].join("\n");
    expect(lines(supported, "no-hand-rolled-list")).toEqual([]);
  });

  it("no-utility-layout and no-hand-rolled-surface read a className template spread over lines", () => {
    const wrapped =
      "<Flex>\n  <div\n    className={`\n      ${base}\n      rounded-md border\n      flex\n    `}\n  />\n</Flex>";
    expect(lines(wrapped, "no-utility-layout")).toEqual([3]);
    expect(lines(wrapped, "no-hand-rolled-surface")).toEqual([3]);
  });
});

/**
 * gh#739 — `icon-button-needs-name` read only the OPENING tag, so the most standard way to name an
 * icon button was reported as unnamed:
 *
 *     <Button size="icon"><Trash2Icon aria-hidden="true" /><span className="sr-only">…</span></Button>
 *
 * That button HAS a name, computed per the Accessible Name and Description Computation §2F,
 * "name from content": the `aria-hidden` glyph contributes nothing, the visually-hidden text
 * (clipped, not `display:none`, not `aria-hidden`) contributes everything. A consumer measured 5/5
 * false positives in one repo, and the literal fix the message asked for — adding `aria-label` on
 * top — leaves TWO name sources free to drift apart.
 */
describe("icon-button-needs-name reads the children too (gh#739)", () => {
  /** Every line this one rule reports for a fixture. ONE CLI process per source (gh#711). */
  function iconButtonLines(source: string) {
    return (
      JSON.parse(audit(source).output) as { findings: { rule: string; line: number }[] }
    ).findings
      .filter((f) => f.rule === "icon-button-needs-name")
      .map((f) => f.line);
  }

  it("stays quiet on every shape that already carries a name", () => {
    const named = [
      // the shape from the issue: aria-hidden glyph + visually-hidden text
      '<Button variant="ghost" size="icon" onClick={() => remove(id)}>',
      '  <Trash2Icon aria-hidden="true" />',
      '  <span className="text-xs sr-only">{t("branches.delete")}</span>',
      "</Button>",
      // the library's own primitive for the same thing (VisuallyHidden renders span.sr-only)
      '<Button size="icon">',
      '  <Trash2Icon aria-hidden="true" />',
      '  <VisuallyHidden>{t("branches.delete")}</VisuallyHidden>',
      "</Button>",
      // a bare i18n expression, and plain text
      '<Button size="icon">{t("branches.delete")}</Button>',
      '<Button size="icon">Delete</Button>',
      // author-supplied name on the opening tag — what the rule accepted before
      '<Button size="icon" aria-label={t("branches.delete")}>',
      '  <Trash2Icon aria-hidden="true" />',
      "</Button>",
      // asChild: the name is on the element the button renders as
      '<Button asChild size="icon">',
      '  <a href="/x" aria-label={t("branches.open")}>',
      '    <ExternalLinkIcon aria-hidden="true" />',
      "  </a>",
      "</Button>",
    ].join("\n");
    expect(iconButtonLines(named)).toEqual([]);
  });

  it("still reports a button whose content contributes no name at all", () => {
    const unnamed = [
      // only an aria-hidden glyph
      '<Button size="icon">',
      '  <Trash2Icon aria-hidden="true" />',
      "</Button>",
      // the text itself is hidden from the accessibility tree
      '<Button size="icon">',
      '  <span aria-hidden="true">{t("branches.delete")}</span>',
      "</Button>",
      // a glyph with no name of its own contributes nothing either
      '<Button size="icon">',
      "  <Trash2Icon />",
      "</Button>",
      // an expression renders the elements it holds, not its own scaffolding
      '<Button size="icon">{open ? <ChevronUpIcon /> : <ChevronDownIcon />}</Button>',
      // prettier's whitespace is not a name
      '<Button size="icon">{" "}</Button>',
      // no children at all
      '<Button size="icon" onClick={() => toggle()} />',
    ].join("\n");
    expect(iconButtonLines(unnamed)).toEqual([1, 4, 7, 10, 11, 12]);
  });
});

/*
 * gh#740 shipped `Card asChild` so a consumer could render "the whole card as one control" — the
 * shape `hoverable`'s own docblock had been prescribing with no way to spell it. The audit was
 * never told, so the documented answer still came back as an error and the consumer that filed
 * the gap (godx-jp/shoots-gemba#8) had no legal move: `<button><Card/></button>` is `no-raw-button`,
 * an `onClick` on the Card div is what the docblock forbids, and `ListRow asChild` wants an `href`
 * this call site does not have (it navigates through a navigator).
 *
 * `Card.asChild`'s docblock names the child shape in as many words — "a card rendered as an `<a>`
 * or a `<button>`" — so a raw tag borrowed by an `asChild` primitive is the prescription, not the
 * violation. The tests below pin BOTH directions, because an exemption that swallows real raw
 * controls would be worse than the contradiction it fixes.
 */
describe("a raw element borrowed by an `asChild` primitive is the prescribed shape", () => {
  const rawButtonLines = (source: string): number[] =>
    (JSON.parse(audit(source).output) as { findings: { rule: string; line: number }[] }).findings
      .filter((finding) => finding.rule === "no-raw-button")
      .map((finding) => finding.line);

  it("does not flag the child of `<Card asChild>`, on one line or with prettier-wrapped attributes", () => {
    const source = [
      "<Card asChild hoverable>", //                                     1
      '  <button type="button" onClick={() => nav.push({})}>', //        2  prescribed
      "    <CardContent>one line</CardContent>", //                      3
      "  </button>", //                                                 4
      "</Card>", //                                                     5
      "<Card", //                                                       6
      "  asChild", //                                                   7
      "  hoverable", //                                                 8
      ">", //                                                           9
      '  <button type="button" onClick={() => nav.push({})}>', //       10  prescribed, wrapped
      "    <CardContent>wrapped</CardContent>", //                      11
      "  </button>", //                                                 12
      "</Card>", //                                                     13
    ].join("\n");

    expect(rawButtonLines(source)).toEqual([]);
  });

  it("still flags a raw button that is NOT a borrowed element", () => {
    const source = [
      "<div>", //                                                        1
      '  <button type="button">a real raw control</button>', //          2  violation
      "</div>", //                                                       3
      "<Card asChild>", //                                               4
      '  <a href="/x">fine</a>', //                                      5
      "</Card>", //                                                      6
      // The card has CLOSED — `</Card>` starts no component, so nothing is borrowed here.
      '<button type="button">after the card closed</button>', //         7  violation
      "<Card hoverable>", //                                             8  no asChild at all
      '  <button type="button">not borrowed</button>', //                9  violation
      "</Card>", //                                                     10
    ].join("\n");

    expect(rawButtonLines(source)).toEqual([2, 7, 9]);
  });
});
