import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

const script = join(process.cwd(), "scripts/ui-audit.mjs");

function audit(source: string, framework = false, path?: string, filename = "sample.tsx") {
  const cwd = mkdtempSync(join(tmpdir(), "godx-ui-audit-"));
  try {
    writeFileSync(
      join(cwd, "package.json"),
      JSON.stringify({ name: framework ? "@godxjp/ui" : "consumer" }),
    );
    const directory = path ?? (framework ? "src" : "resources/js/pages");
    mkdirSync(join(cwd, directory), { recursive: true });
    writeFileSync(join(cwd, directory, filename), source);
    const result = spawnSync(process.execPath, [script, "--format", "json"], {
      cwd,
      encoding: "utf8",
    });
    return { status: result.status, output: result.stdout };
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
}

describe("consumer audit CLI regressions", () => {
  /**
   * `\p{Extended_Pictographic}` covers U+00A9 ©, U+00AE ® and U+2122 ™, and all three are
   * `Emoji_Presentation=No` — typographic marks that predate emoji and default to text
   * presentation. None of the reasons in the rule's own message reaches them: a copyright line
   * does not break on Win/Linux and does not pollute an accessible name. The catalog's own
   * CenteredShell recipe was flagged for the `©` in its footer, and so is every consumer that
   * ships one.
   *
   * With U+FE0F after them they are asking for emoji presentation on purpose, so they stay caught.
   */
  it("does not call ©, ® or ™ an emoji, but still catches them with a VS16 selector", () => {
    expect(audit("<Text>\u00a9 2026 GodX</Text>").output).not.toContain('"no-emoji-in-ui"');
    expect(audit("<Text>Acme\u2122 \u00ae</Text>").output).not.toContain('"no-emoji-in-ui"');
    expect(audit("<Text>\u00a9\ufe0f 2026</Text>").output).toContain('"no-emoji-in-ui"');
    expect(audit("<Text>Shipped \u2705</Text>").output).toContain('"no-emoji-in-ui"');
    expect(audit("<Text>\ud83c\udf89</Text>").output).toContain('"no-emoji-in-ui"');
  });

  it("distinguishes framework test support and API prose from shipped JSX", () => {
    expect(audit("<button>Fixture</button>", true, "src/test").output).not.toContain(
      '"no-raw-button"',
    );
    expect(audit("<button>Action</button>", true, "src/pages").output).toContain('"no-raw-button"');
    expect(
      audit(
        'const description = "A <button> owns the action — never a link";',
        true,
        "src/props",
        "registry.ts",
      ).status,
    ).toBe(0);
    expect(audit('console.warn("Missing name — check your props");').output).not.toContain(
      '"no-em-dash-in-copy"',
    );
    expect(audit("<Text>First\n — second</Text>").output).toContain('"no-em-dash-in-copy"');
    expect(audit('<Input placeholder="—" />').output).not.toContain('"no-em-dash-in-copy"');
    expect(audit('<Input placeholder="First — second" />').output).toContain(
      '"no-em-dash-in-copy"',
    );
  });

  it("allows physical animation directions but still catches physical layout", () => {
    expect(audit('const classes = "data-[side=left]:slide-in-from-right-2";').output).not.toContain(
      '"no-physical-direction"',
    );
    expect(audit('const classes = "slide-in-from-right-2 pr-4";').output).toContain(
      '"no-physical-direction"',
    );
    expect(
      audit(
        '/* rtl-ignore: sheet side names a physical edge */\nconst classes = "right-0 border-l";',
      ).output,
    ).not.toContain('"no-physical-direction"');
  });

  it("recognizes compiled email tokens without allowing handwritten overrides", () => {
    const source =
      '// AUTO-GENERATED by scripts/gen-email-tokens.mjs — do not edit.\nconst tokens = { "--email-shell-padding": "32px" };';
    expect(audit(source, true, "src/email", "tokens.generated.ts").output).not.toContain(
      '"no-off-scale-token-value"',
    );
    expect(audit(source, false, "resources/js/pages", "tokens.generated.ts").output).toContain(
      '"no-off-scale-token-value"',
    );
    expect(
      audit(
        'const tokens = { "--email-shell-padding": "32px" };',
        true,
        "src/email",
        "tokens.generated.ts",
      ).output,
    ).toContain('"no-off-scale-token-value"');
  });

  it("does not interpret template substitutions or comparisons as currency text", () => {
    expect(
      audit("const html = `<p>${copy}</p>`;", true, "docs/foundation", "email.ts").output,
    ).not.toContain('"hardcoded-currency"');
    expect(
      audit("<Calendar footer={days.length > 0 ? `Selected: ${days.length}` : null} />").output,
    ).not.toContain('"hardcoded-currency"');
    expect(audit('<Text title={count > 0 ? "yes" : "no"}>${amount}</Text>').output).toContain(
      '"hardcoded-currency"',
    );
  });
  it("reads class-shaped rules from class expressions only, not prose (#406)", () => {
    // Copy, an i18n value or a JSX text node that merely SPELLS a utility is not a class.
    expect(audit("const note = 'chuỗi có chữ gap-3 trong đó';").output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<Text>văn bản JSX nhắc gap-3</Text>").output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit('const messages = { hint: "Total gap-3 items" };').output).not.toContain(
      '"no-utility-spacing"',
    );
    expect(audit('<Text title="Spacing: use gap-3">Read me</Text>').output).not.toContain(
      '"no-utility-spacing"',
    );
    // …and the text of an element that DOES carry a class is still only text.
    const mixed = audit('<div className="flex">gap-3 items</div>').output;
    expect(mixed).toContain('"no-utility-layout"');
    expect(mixed).not.toContain('"no-utility-spacing"');
  });

  it("still catches a class wherever a class can actually be written (#406)", () => {
    expect(audit('<div className="gap-3" />').output).toContain('"no-utility-spacing"');
    expect(audit('<div className={cn("gap-3", isWide && "p-2")} />').output).toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<div className={clsx(\n  active && `gap-3`,\n)} />").output).toContain(
      '"no-utility-spacing"',
    );
    expect(audit("<div className={`pr-4 ${extra}`} />").output).toContain(
      '"no-physical-direction"',
    );
    expect(audit('const baseClass = "space-x-2";').output).toContain('"no-space-xy"');
    expect(audit('const columns = [{ className: "text-white" }];').output).toContain(
      '"raw-white-black"',
    );
    // A class MAP under its conventional names — the shape `cva()` is not used for.
    expect(
      audit('const statusStyles: Record<string, string> = {\n  spam: "bg-red-100",\n};').output,
    ).toContain('"no-raw-palette-color"');
    expect(audit('const badgeVariants = {\n  lead: "dark:bg-red-500/15",\n};').output).toContain(
      '"no-dark-color-override"',
    );
  });

  it("suppresses a block only when a reason is given, and only for that rule (#406)", () => {
    const block = (begin: string) =>
      audit(
        `${begin}\nconst aClass = "gap-3";\nconst bClass = "p-2";\n// ui-audit-disable-end no-utility-spacing\nconst cClass = "gap-4";`,
      );

    // Reason present → one marker covers every line of the block.
    const suppressed = block(
      "// ui-audit-disable-begin no-utility-spacing — legacy grid, tracked in gh#123",
    );
    expect(suppressed.output).toContain('"line": 5'); // the line AFTER the block still reports
    expect(suppressed.output.match(/"no-utility-spacing"/g)).toHaveLength(1);

    // Reason missing, or too short to say anything → the finding stands on all three lines.
    for (const begin of [
      "// ui-audit-disable-begin no-utility-spacing",
      "// ui-audit-disable-begin no-utility-spacing — why",
    ]) {
      expect(block(begin).output.match(/"no-utility-spacing"/g), begin).toHaveLength(3);
    }

    // A block names ONE rule; every other rule keeps reporting inside it.
    const scoped = audit(
      "// ui-audit-disable-begin no-utility-spacing — spacing is deliberate here\n" +
        'const aClass = "gap-3 bg-red-500";\n' +
        "// ui-audit-disable-end no-utility-spacing",
    );
    expect(scoped.output).not.toContain('"no-utility-spacing"');
    expect(scoped.output).toContain('"no-raw-palette-color"');

    // An unclosed block runs to the end of the file.
    expect(
      audit(
        "// ui-audit-disable-begin no-utility-spacing — whole fixture is legacy markup\n" +
          'const aClass = "gap-3";\nconst bClass = "p-2";',
      ).output,
    ).not.toContain('"no-utility-spacing"');
  });

  it("scans framework defaults and still detects a violation", () => {
    const result = audit('<input type="text" />', true);
    expect(result.status).toBe(1);
    expect(result.output).toContain('"no-raw-input"');
    expect(result.output).toContain("src/sample.tsx");
  });

  it("allows primitive native controls without exempting consumer screens or docs", () => {
    expect(audit('<input type="text" />', true, "src/components/data-entry").status).toBe(0);
    expect(audit('<input type="text" />', true, "docs/data-entry").output).toContain(
      '"no-raw-input"',
    );
    expect(audit('<input type="text" />', false, "resources/js/pages").output).toContain(
      '"no-raw-input"',
    );
  });

  it("allows hidden form encoding but rejects visible and unknown input types", () => {
    expect(audit('<input\n name="id"\n type="hidden" value="7" />').status).toBe(0);
    expect(audit("<input type='hidden' name='id' />").status).toBe(0);
    for (const source of [
      '<input type="text" />',
      "<input\n type={kind}\n />",
      "<input />",
      "<input hidden />",
    ]) {
      expect(audit(source).output, source).toContain('"no-raw-input"');
    }
  });

  it("does not flag template URLs or generics as hardcoded currency (#601)", () => {
    const quiet = [
      "const result = await context.request<TurnResult>(`/chat/${queued.turn_id}`);",
      "const path = `/api/${id}/x`;",
      "const joined = `${a}-${b}`;",
      "const Box = styled.div`padding: ${space}px`;",
    ];
    for (const source of quiet) {
      expect(audit(source).output, source).not.toContain('"hardcoded-currency"');
    }
    expect(audit("<span>${price}円</span>").output).toContain('"hardcoded-currency"');
    expect(audit("<Text>¥{amount}</Text>").output).toContain('"hardcoded-currency"');
  });

  it("does not mistake Markdown interpolation for JSX currency", () => {
    expect(audit("const quote = lines.map((line) => `> ${line}`);").status).toBe(0);
    expect(audit("<Button onClick={() => router.post(`/view/${id}`)}>Save</Button>").status).toBe(
      0,
    );
    for (const source of [
      "<Text>${amount}</Text>",
      '<Text\n tone="muted">\n¥{amount}</Text>',
      "<Text>{amount}円</Text>",
      "<Text>Total: ${amount}</Text>",
      "<>${amount}</>",
      '<Text title="a > b">${amount}</Text>',
      "<Button onClick={() => save()}>${amount}</Button>",
    ]) {
      expect(audit(source).output, source).toContain('"hardcoded-currency"');
    }
  });
});

it("rejects Select onChange and accepts the supported value callback", () => {
  expect(audit("<Select options={options} onChange={setValue} />").output).toContain(
    '"value-callback-on-value-change"',
  );
  expect(audit("<Select options={options} onValueChange={setValue} />").output).not.toContain(
    '"value-callback-on-value-change"',
  );
});

describe("card composition (godx-jp/id#496, #498)", () => {
  it("does not call a Form-wrapped body a missing body", () => {
    // The only correct composition for a card whose submit button lives in CardFooter: the <form>
    // has to wrap the content AND the footer, or the button cannot submit it. The rule asked for a
    // Card slot as the IMMEDIATE next element, so it fired on correct code — three times, on a
    // consumer's newest file.
    const wrapped = [
      '<Card>\n<Form onSubmit={s}>\n<CardContent>body</CardContent>\n<CardFooter><Button type="submit">save</Button></CardFooter>\n</Form>\n</Card>',
      '<Card density="tight">\n<>\n<CardContent solo>body</CardContent>\n</>\n</Card>',
    ];

    for (const source of wrapped) {
      expect(audit(source).output, source).not.toContain('"card-needs-content"');
    }
  });

  it("still reports a card with no body at all", () => {
    expect(audit("<Card>\n<Table><tbody /></Table>\n</Card>").output).toContain(
      '"card-needs-content"',
    );
  });

  it("requires flush when the table IS the card body, and only then", () => {
    const bare =
      "<Card>\n<CardContent>\n<DataTable columns={c} data={d} />\n</CardContent>\n</Card>";
    const flush =
      "<Card>\n<CardContent flush>\n<DataTable columns={c} data={d} />\n</CardContent>\n</Card>";
    // A filter bar ABOVE the table makes the body mixed, and there the padding is correct — the
    // trap the reporter hit with a `childElementCount === 1` test.
    const mixed =
      '<Card>\n<CardContent>\n<Flex direction="col" gap="md">\n<FilterBar />\n<DataTable columns={c} data={d} />\n</Flex>\n</CardContent>\n</Card>';

    expect(audit(bare).output).toContain('"card-table-needs-flush"');
    expect(audit(flush).output).not.toContain('"card-table-needs-flush"');
    expect(audit(mixed).output).not.toContain('"card-table-needs-flush"');
  });
});

it("names the replacement primitive in the finding (godx-jp/id#497)", () => {
  // Without this the reader has to ask the catalog which component replaces what they just wrote —
  // one round-trip per finding, and a guess about what to look up.
  const out = audit(
    "<Card>\n<CardContent>\n<DataTable columns={c} data={d} />\n</CardContent>\n</Card>",
  ).output;

  expect(out).toContain('"replacement": "CardContent flush"');
  expect(audit('<button type="button">save</button>').output).toContain('"replacement": "Button"');
});

describe("owned rule file drift (godx-jp/id#513)", () => {
  /** A consumer tree whose `.ai/rules/godxjp-ui.md` claims `stamped` while the package is 23.0.0. */
  function consumerWithStamp(stamped: string) {
    const cwd = mkdtempSync(join(tmpdir(), "godx-ui-stale-"));
    writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: "consumer" }));
    mkdirSync(join(cwd, ".ai", "rules"), { recursive: true });
    mkdirSync(join(cwd, "node_modules", "@godxjp", "ui"), { recursive: true });
    mkdirSync(join(cwd, "resources", "js", "pages"), { recursive: true });
    writeFileSync(
      join(cwd, "node_modules", "@godxjp", "ui", "package.json"),
      JSON.stringify({ name: "@godxjp/ui", version: "23.0.0" }),
    );
    writeFileSync(
      join(cwd, ".ai", "rules", "godxjp-ui.md"),
      `<!-- godxjp-ui:version ${stamped} -->\n`,
    );
    writeFileSync(
      join(cwd, "resources", "js", "pages", "a.tsx"),
      "export const A = () => <Text>a</Text>;\n",
    );
    const result = spawnSync(process.execPath, [script, "--format", "json"], {
      cwd,
      encoding: "utf8",
    });
    rmSync(cwd, { recursive: true, force: true });
    return result.stdout;
  }

  it("reports a rule file three majors behind the package it documents", () => {
    // `ignore-scripts=true` blocks our postinstall, so the file that promises to be rewritten on
    // every upgrade silently is not. An agent then follows rules for components that were deleted.
    const out = consumerWithStamp("19.6.0");

    expect(out).toContain('"owned-rules-stale"');
    expect(out).toContain("19.6.0");
    expect(out).toContain("sync-rules");
  });

  it("says nothing when the file matches the installed package", () => {
    expect(consumerWithStamp("23.0.0")).not.toContain('"owned-rules-stale"');
  });
});

describe("an opening tag that ends its line is still an opening tag (gh#673)", () => {
  /** The line numbers one rule reports for a fixture. */
  function lines(source: string, rule: string, framework = false, path?: string) {
    const report = JSON.parse(audit(source, framework, path).output) as {
      findings: { rule: string; line: number }[];
    };
    return report.findings.filter((f) => f.rule === rule).map((f) => f.line);
  }

  /*
   * Prettier wraps any element wider than printWidth, which leaves `<button` alone on its line. The
   * control rules matched `/<button[\s>]/` ONE LINE at a time, and the newline that follows the tag
   * name is not part of that line, so every wrapped element was invisible. Measured in a consumer
   * app: 0 `no-raw-button` reported while ~166 multi-line `<button` remained.
   */
  it.each([
    [
      "no-raw-button",
      '<Flex>\n  <button\n    type="button"\n    onClick={() => go()}\n  >\n    Go\n  </button>\n</Flex>',
    ],
    [
      "no-raw-select",
      "<Flex>\n  <select\n    value={value}\n    onChange={(e) => set(e.target.value)}\n  >\n    <option />\n  </select>\n</Flex>",
    ],
    [
      "no-raw-input",
      '<Flex>\n  <input\n    type="checkbox"\n    checked={on}\n    onChange={(e) => set(e.target.checked)}\n  />\n</Flex>',
    ],
    ["no-raw-textarea", "<Flex>\n  <textarea\n    rows={3}\n    value={value}\n  />\n</Flex>"],
    [
      "no-raw-table",
      '<Flex>\n  <table\n    aria-label="rows"\n  >\n    <tbody />\n  </table>\n</Flex>',
    ],
  ])("%s reports a multi-line element on the line of its `<`", (rule, source) => {
    expect(lines(source, rule)).toEqual([2]);
  });

  it("still reports the single-line form, once per element", () => {
    expect(lines('<button type="button">Go</button>', "no-raw-button")).toEqual([1]);
    expect(lines("<select><option /></select>", "no-raw-select")).toEqual([1]);
    expect(lines("<table><tbody /></table>", "no-raw-table")).toEqual([1]);
    expect(lines("<textarea />", "no-raw-textarea")).toEqual([1]);
    expect(lines("<button/>", "no-raw-button")).toEqual([1]);
  });

  it("honours ui-audit-disable-next-line above a multi-line element, in both comment forms", () => {
    const element =
      '  <button\n    type="button"\n    onClick={() => go()}\n  >\n    Go\n  </button>';
    expect(
      lines(
        `<Flex>\n  {/* ui-audit-disable-next-line no-raw-button */}\n${element}\n</Flex>`,
        "no-raw-button",
      ),
    ).toEqual([]);
    expect(
      lines(
        `const x = (\n  // ui-audit-disable-next-line no-raw-button\n${element}\n);`,
        "no-raw-button",
      ),
    ).toEqual([]);
    // The directive names ONE rule and covers ONE line: another id, or a blank line between, does not.
    expect(
      lines(
        `<Flex>\n  {/* ui-audit-disable-next-line no-raw-select */}\n${element}\n</Flex>`,
        "no-raw-button",
      ),
    ).toEqual([3]);
    expect(
      lines(
        `<Flex>\n  {/* ui-audit-disable-next-line no-raw-button */}\n\n${element}\n</Flex>`,
        "no-raw-button",
      ),
    ).toEqual([4]);
  });

  it("does not match components, longer tag names, closing tags or comments", () => {
    const quiet = [
      '<ButtonGroup\n  size="sm"\n>\n  <Button\n    onClick={go}\n  >\n    Go\n  </Button>\n</ButtonGroup>',
      "<Input\n  value={v}\n/>",
      "<Select\n  value={v}\n  onValueChange={set}\n/>",
      "<buttonish\n  a={1}\n/>",
      "<inputs\n  a={1}\n/>",
      "<selection\n  a={1}\n/>",
      "<Flex>\n  {label}\n</button\n>",
      '/*\n * <button\n *   type="button"\n */\nconst a = 1;',
      "// <select\nconst b = 2;",
    ];
    // ONE audit per source, read for all three rules. This loop used to spawn the CLI once per
    // (source, rule) pair — 27 processes, measured past vitest's 8s default on a loaded CI runner,
    // which failed the 27.1.0 merge commit on load alone. The findings are the same either way.
    for (const source of quiet) {
      const report = JSON.parse(audit(source).output) as { findings: { rule: string; line: number }[] };
      for (const rule of ["no-raw-button", "no-raw-input", "no-raw-select"]) {
        const found = report.findings.filter((f) => f.rule === rule).map((f) => f.line);
        expect(found, `${rule}: ${source}`).toEqual([]);
      }
    }
  });

  it("keeps the framework's own primitives exempt, and nothing else", () => {
    const wrapped = '<button\n  type="button"\n/>';
    expect(lines(wrapped, "no-raw-button", true, "src/components/general")).toEqual([]);
    expect(lines(wrapped, "no-raw-button", true, "docs/general")).toEqual([1]);
  });

  /* The same line-bound defect, in the other rules anchored on something that can span lines. */
  it("manual-field-helper sees a wrapped <p>", () => {
    expect(
      lines(
        '<Flex>\n  <p\n    className="text-xs text-muted-foreground"\n  >\n    Hint\n  </p>\n</Flex>',
        "manual-field-helper",
      ),
    ).toEqual([2]);
  });

  it("hand-rolled-close-glyph sees a glyph on its own line, and still accepts a named one", () => {
    expect(
      lines(
        '<Flex>\n  <span className="close">\n    ×\n  </span>\n</Flex>',
        "hand-rolled-close-glyph",
      ),
    ).toEqual([2]);
    expect(
      lines(
        '<Flex>\n  <span aria-hidden="true">\n    ×\n  </span>\n  <VisuallyHidden>未実施</VisuallyHidden>\n</Flex>',
        "hand-rolled-close-glyph",
      ),
    ).toEqual([]);
  });

  it("no-utility-layout and no-hand-rolled-surface read a className template spread over lines", () => {
    const wrapped =
      "<Flex>\n  <div\n    className={`\n      ${base}\n      rounded-md border\n      flex\n    `}\n  />\n</Flex>";
    expect(lines(wrapped, "no-utility-layout")).toEqual([3]);
    expect(lines(wrapped, "no-hand-rolled-surface")).toEqual([3]);
  });
});
