/** Barrel — all vocabulary prop types. */

export type {
  ClassNameProp,
  ChildrenProp,
  IdProp,
  OpenProp,
  DefaultOpenProp,
  OnOpenChangeProp,
  HandlerProp,
  PendingProp,
  RequiredProp,
  DisabledProp,
  LabelProp,
  HelperProp,
  ErrorProp,
  ErrorBagProp,
  PlaceholderProp,
  NameProp,
  ValueProp,
  DefaultValueProp,
  OnValueChangeProp,
  OnChangeProp,
  OnClickProp,
  AsChildProp,
  FlushProp,
  WidthProp,
  ControlWidthProp,
  AllowClearProp,
  MaxTagCountProp,
  MaxTagPlaceholderProp,
  NotFoundContentProp,
  PopupMatchWidthProp,
} from "./shared.prop";

export type {
  TitleProp,
  SubtitleProp,
  StatusProp,
  DescriptionProp,
  ExtraProp,
  FooterProp,
  ActionProp,
  IconProp,
  ConfirmLabelProp,
  CancelLabelProp,
  ActionsProp,
  EmptyMessageProp,
} from "./content.prop";

export type {
  PageDensityProp,
  PageContainerVariantProp,
  CenteredShellWidthProp,
  CenteredShellAlignProp,
  CenteredShellPresetProp,
  ErrorSurfaceModeProp,
  ErrorSurfaceStatusProp,
  AuthShellPresetProp,
  MobileShellHeightProp,
  MobileShellWidthProp,
  OrientationProp,
  TableDensityProp,
  DensityProp,
  GapNameProp,
  PadProp,
  PadRawProp,
  PadSides,
  GapProp,
  GapStepProp,
} from "./layout.prop";

export type {
  ButtonVariantProp,
  ButtonSizeProp,
  BadgeVariantProp,
  AppSettingPickerAppearanceProp,
  AppSettingToggleAppearanceProp,
  ShapeProp,
  AvatarShapeProp,
  TextSizeProp,
  TextToneProp,
  FontWeightProp,
  HeadingLevelProp,
  TextAlignProp,
  TextWhitespaceProp,
  TypographyTypeProp,
  TitleLevelProp,
  TypographyCopyConfigProp,
  TypographyEditConfigProp,
  TypographyEllipsisConfigProp,
  TypographyActionsConfigProp,
  SizeProp,
  ControlStatusProp,
  ControlVariantProp,
  FormLayoutProp,
  DescriptionsLayoutProp,
  BreakpointProp,
  ConfirmVariantProp,
  ToneProp,
  AlertVariantProp,
  SortDirectionProp,
  ColumnAlignProp,
  SortStateProp,
  RevealDelayProp,
  ActivityVariantProp,
  ActivityAnnounceProp,
} from "./interaction.prop";

export type {
  BreadcrumbItemProp,
  BreadcrumbProp,
  BreadcrumbItemMenuProp,
  BreadcrumbItemMenuEntryProp,
  BreadcrumbSeparatorProp,
  BreadcrumbItemRenderProp,
} from "./navigation.prop";

export type {
  GetRowIdProp,
  GetRowLabelProp,
  OnRowClickProp,
  ColumnDefProp,
  TablePresetProp,
  TableColumnPriorityProp,
  TableCellIndentProp,
  SelectedIdsProp,
  OnSelectChangeProp,
  OnTableDensityChangeProp,
  TableRowToneProp,
  RowToneProp,
  OnSortChangeProp,
  OnSearchChangeProp,
  OnClearFiltersProp,
  HasActiveFiltersProp,
  StickyProp,
  ColumnFixedProp,
  ColumnFilterValueProp,
  ColumnFilterItemProp,
  ColumnFilterStateProp,
  OnColumnFilterChangeProp,
  ColumnCompareProp,
  ColumnSorterProp,
  TableSelectionItemProp,
  TableRowSelectionProp,
  TableExpandableProp,
  TableSummaryProp,
  TableScrollProp,
  TableStickyProp,
  OnRowProp,
  TablePaginationProp,
  DescriptionsColumnProp,
  DescriptionsSpanProp,
  DescriptionsItemsProp,
} from "./data.prop";
